apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  path: ./platform/weave-gitops/_operators
  prune: true
  wait: true
  timeout: 10m
  postBuild:
    substitute:
      namespace_name: weave-gitops
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
      # - kind: Secret
      #   name: cluster-secrets
      #   optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops-resource-configs
  namespace: flux-system
spec:
  dependsOn:
  - name: weave-gitops
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  path: ./platform/weave-gitops/_resource-configs
  prune: true
  wait: true
  timeout: 10m
  postBuild:
    substitute:
      namespace_name: weave-gitops
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    # - kind: Secret
    #   name: cluster-secrets
    #   optional: true
