apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptrace
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: ${cert_manager_issuer_name}
      hosts:
      - host: uptrace.${wildcard_ingress_subdomain}
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: uptrace-tls
        hosts:
        - uptrace.${wildcard_ingress_subdomain}
