apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@no-reply.com
    # This key doesn't exist, cert-manager creates it
    privateKeySecretRef:
      name: letsencrypt-aws-issuer
    solvers:
    - selector:
        dnsZones:
        - "${aws_route53_dns_zone}"
      dns01:
        route53:
          region: "${aws_route53_region}"
          secretAccessKeySecretRef:
            name: letsencrypt-aws-secret
            key: secret-access-key
          accessKeyIDSecretRef:
            name: letsencrypt-aws-secret
            key: access-key-id
