apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-aws-secret
  namespace: cert-manager
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
stringData:
  access-key-id: "${aws_route53_key_id}"
  secret-access-key: "${aws_route53_key_secret}"
