apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: flux-system
spec:
  interval: 4h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector-deployment
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=opentelemetry}
  chart:
    spec:
      chart: opentelemetry-collector
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: ${opentelemetry_collector_version}
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
  values:
    imagePullSecrets:
    - name: docker-hub-regcred
    mode: deployment
    replicaCount: 1
    presets:
      clusterMetrics:
        enabled: true
      kubernetesEvents:
        enabled: true
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
      processors:
        batch:
          send_batch_size: 10000
          timeout: 10s
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
      exporters:
        otlp/uptrace:
          endpoint: uptrace-grpc.${management_cluster_ingress_subdomain}:14317
          tls:
            insecure: true
          headers:
            uptrace-dsn: 'http://project2_secret_token@localhost:14317/2'
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/uptrace]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/uptrace]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/uptrace]

