apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: flux-system
spec:
  interval: 4h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector-deployment
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=opentelemetry}
  chart:
    spec:
      chart: opentelemetry-collector
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: "0.80.1"
  interval: 1h
  values:
    imagePullSecrets:
    - name: regcred
    mode: deployment
    replicaCount: 1
    presets:
      clusterMetrics:
        enabled: true
      kubernetesEvents:
        enabled: true
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
      processors:
        batch:
          send_batch_size: 10000
          timeout: 10s
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
      exporters:
        otlp/uptrace:
          endpoint: uptrace-grpc.${wildcard_ingress_subdomain}
          tls:
            insecure: false
          headers:
            uptrace-dsn: 'http://project2_secret_token@localhost:14317/2'
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/uptrace]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/uptrace]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/uptrace]

