apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: milvus-operator
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: cert-manager-resource-configs
  - name: ingress-nginx
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./platform/milvus-operator/_operators
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: milvus
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: milvus-operator-resource-configs
  namespace: flux-system
spec:
  dependsOn:
  - name: milvus-operator
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./platform/milvus-operator/_resource-configs
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: milvus
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false
