apiVersion: v1
kind: Namespace
metadata:
  name: milvus
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: milvus
  namespace: flux-system
spec:
  interval: 4h
  url: https://zilliztech.github.io/milvus-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus-vectordb
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=milvus}
  chart:
    spec:
      chart: milvus
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: milvus
      version: ${milvus_version}
  interval: 1h
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
  values: {}
