# Ref: https://github.com/devcontainers/ci/issues/191
FROM mcr.microsoft.com/devcontainers/base:alpine

LABEL org.opencontainers.image.title="cloud-native-utils"
LABEL org.opencontainers.image.description="Cloud Native Utils"

