kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:kk9sFp4lv2kIZs9edFVirprYldBD/9ie/L7xq4kKc2A2M/cud2AxkG4UWQZWA1p6kWuaXLE=,iv:P9rZnjkUBz0miGn9VULA4y94GaWQBSssKN0qfKsF7Z0=,tag:Pyj2yp29p8BLHRUhtYqnrQ==,type:str]
    github_user: ENC[AES256_GCM,data:VkXxSOTL94O24DyqJ3g=,iv:NHvp92M5KxvVMo25wda6x6h8gocDq3mxFPvqy7DCk0Q=,tag:G9KmT9G1gC48jlG5gljmdg==,type:str]
    github_api_token: ENC[AES256_GCM,data:qsI2hhPyzEGy3jUDL0IVCLNAtV1OMdWgmIhFMLIFtjH20mDOrak9Uw==,iv:pfOaBmFuXhEStFZsenSNp96G8T+bMH8rebykBxt4EEY=,tag:1oWNSmDZTtRNMevg/BdCIg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:5kxBp4f0hz4=,iv:Dr5oiLXl7op0AADj4gS3pXpqtu0FB2cd5OAT7BBB+fM=,tag:P45fgQLJrKB1U/bWP1XCuA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:DCuhC/UgESlB1XMg1cyPGNWKwFuXQDLKVnTPESNShIbV6m28,iv:HRxklEeqstzYnOmrOg+YTNdVlJP91HzArrIVs0gMZpg=,tag:1lzgDruKgbfg989rfBhCtg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:WX8jErG9igUk5cHzRR/ITuSzhInd4BY=,iv:XDJJAhzF/e421sqg23pFDIY9c0jLDRd7dwruqm7vR3E=,tag:A9vLglU3xX7IzQv3ziqA3Q==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:VsLNYwOjtjDl1P2uj8U=,iv:YNHkLnzVuZ9m8VxzSBaUf+xdWjpzKlu6kSopDCrSQbA=,tag:jDjXO5q63RpQ4d72Rg1Www==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:zO2XBp23RYYD+WyFIUx0JR/qvELvcrdD6QWhryQkCWa4xA==,iv:9ZsQZMQ+cVTQnxuwXhrDZdGJ6hY9WPI34JmBL2ElFOc=,tag:R4nsRaZM6zXgjfesojr26w==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:qAZP9gf8AjxMYFu8c6qfZLMj4PEdLy9c1jdI3xUV5ZOcLQ==,iv:E+Qh6eZS+zrOoIl2lHyzOvmbkn1tGmAeGYYkWrMp8y0=,tag:i8+WxBByBYMQoWzcQ9Belg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:6wezON7bDpMIK6VIlpM=,iv:Y/zFT9GJZHcS2FsncwHyZhgHAAXLG97E59fOSghcvKU=,tag:cqIeTl55GVSu2H3NrLof3Q==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:ypORvh+5MIDAdzeFHkasTK5ThQKLzrJ7HNMEmVinaN6yhJW4HZ8=,iv:NN4ODAGdpd+C6DvIfWvfGRxfWLK/M0D9BngoumLcq7U=,tag:JJdNBLEcy0Heu3ziKwT2OQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMElXYTE3Y0NjK3E2eHFR
            eWJvUDltMmpYMVZCY3Z6M3NUSkRHTWcxMjFJCjQ4S0tYK2Q1UUJEZ0J3VUQ5SmpY
            YllVNVc5UUtveFZaemJMRGpNeFhySFUKLS0tIDFXYmNPa01tRjZ2bXlGSUJLc1VT
            bW1xbkd6NFFBZm1ROHlwUHVRYzdVcTAKphdso1gj69tc2W7FfdoeLFLVwXf2ubyS
            XNLKAj1sfYCVpBHLbx7Pg+76nIhMSvt83WXht/pir7CM9cCjS0HV8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T21:12:13Z"
    mac: ENC[AES256_GCM,data:ZnHsViZ1O+Bkw8Msjdmtz1k86K6292bGx7LvG3mNYa3eCkrghp0Ag9rBLZxIrxPh3Sy09SwhjnHxSu4ALYeGXv7CBmt/lFKq6aiPDN3mJxmoukdibE+vFsrg5G8vAoZZmd+70kc2Ldu8dd1YH7LrF06E1n1uRE3C0vh/Co3zbis=,iv:0e34+fk6AVrPGfWGGnTn/P/+Py2AAiv/36KXhVFrqnU=,tag:wRokayluEO5LjLYfygyUfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
