kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:VcDaBvCpaCvMntucOOmiT+fM+1W6+gPQzEx4Ks4HpiIQyRJ8VHgMDrQmIPSaVT94Cga/r6k=,iv:SnZVPijFVePb3hPlEdkXJXrvyqbLo36i4Ogpt6yG8c4=,tag:ifFiRFG35SLYAk2syF8eRg==,type:str]
    github_user: ENC[AES256_GCM,data:1uTZp1TrHWR+Be/qA/w=,iv:Pn10PWaZjaFkrXD6rTl3OBnrNuCntsfAa+++BN+2pGY=,tag:eOhXreipe8VcCzznfCCrUQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:nN/MSr358RdxtOhV3o3AhE76MfD6fzaDcls6dLCYx0jPBXS8/8aFvg==,iv:aB6x5WtsyIZGV6C8Rl1T32OJtu0ed8p2VTQT6/KiE2M=,tag:Lm2yRzdJiT9LARbk8w9aGw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:e75D42b9+Pc=,iv:qJTmHk7CcG2+215/Lyv5Dr3jmNOBhGkUPamZmKe/tdQ=,tag:no8zaPXU5HMSUsVqKTINMA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:Vbt5rLWYuBTNJD1sKYSoHyrMBbI0GETriXcbStKnJiJE+bpw,iv:XPuUFWO2nGeI9QbYbzhXLWzeIPpdwDf31TH59cG1idc=,tag:ul5hjGeb+le9KOrzuGFVRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMEZ0YVpSYWt5VlpQUUVJ
            YXNXM09IeWV6dFF1VUJteUY2Q1A4aGRkNGxnCm02RFlTNDhIZS9KQ0NrNEQ5Y2NN
            dzBrdXZUbUUxZjJoZ3lEczRjN0wvRG8KLS0tIFNqaS8zNTZNOGs2ME1kRTkzMVFU
            QllOTmlzanY3dElCWk5VSDZ2ZWkrR1EKdtotVWlM6J6vkMAowSqh/xVn6Od+fpK6
            tDZFY6M2IIi/JLqqST/XsG77cYz/2ivezPiB7Fg1Y9ngExNfvFqBtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T16:55:03Z"
    mac: ENC[AES256_GCM,data:iH6Um2nV0aX0F0LnJ5hoqffZ9QvQfO6Pisqs2tNzO3TbgKBmhvbYNwPXygHYFIDrJj4ddXQQ03uvKVVHqIWv8qz58JroSopDIMusoCxSPhH4CY7WHYcutjTh6cOG5VEMX5KsWH88Cpqjl5XICSO7Ue3C8RQ6Ttox2wAdrNlzGXQ=,iv:h4X+VLPDNJ9UOwvXUUewJIagG2xfGa3lJLwLuK8CQiA=,tag:ebtELfwTY77E16yEusMMNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
