kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:3SeoCI0sJuC7daLCaiVWjl2tSVN1j82VHuaJwy4b/miK99ov0yTJWZ0FQqCVG16i3NujjDI=,iv:LqkphZwappcRBCfzyaIWBS+MnQ0KfGxssEMrBmd7I+U=,tag:m7tBynBkYh0+k59i2MXVVA==,type:str]
    github_user: ENC[AES256_GCM,data:E4tnCCY/HNU0jzOohrg=,iv:D81II1ag5nZ4YCCH3f6sMucbB0A+HO7M0K8fToTuU+E=,tag:M1A3YQUHw2mb86CU34ezvQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:Gmm7qqwckiuQcllm/kUv0klcQZBGGOG5pw1ioJQkf6F0jzpuh4orzQ==,iv:BS0Yzv+JRW5+U0EXZ3O4zrPlFbGyd7QAgXJU+tma6UE=,tag:sRvkuDmg7J4XfPLhKDYxWQ==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:cIfad5FgZJQ=,iv:/mxqQVLvBKaYn3FAqVI5Snonamq0wE1hfwq4TtrYwhA=,tag:T8fLvXvKkRZtB81aGoOCfw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:mBiosxGMA8bhRsOHiXPy/SnwkouvbDgrkP6QnJE8yvcEvfEo,iv:qK98uOTf2qTN1h4CBl1UQtU/tv6DgYnQnaRN6CF/Thw=,tag:A7ydMPqjEqYxcUF4+Xe+lA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Tkg3dGllK3lOdWJmV1Jj
            REI0aVd3ellWTW5YNHhCNDNzdUdCMGIyVWpNClhGbngwT2ErUktYRmN6OGc4aVdZ
            dmJsM0gzcTlibU5wMzRzd0NVd01MeEkKLS0tIFU2RDZLQUhOK3haUG8zOE5zK2da
            ck1FblJNZDZYWmZISmVqYlJOUVBSaEUKArxI8LjxMyPbnRWSQs5yHi8pBcIHexu8
            Va1W3+gfSJeHmJGVdORkttPso91cjzLdpInbI1/RPr3rZgwWAsBDCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T01:31:03Z"
    mac: ENC[AES256_GCM,data:KYag+XuOAo58h4mjALX5p6C866tOgcSHwgbWS5PBVzRwj00ZUCGDX79ulqReNe2eLSDFd/kIrgx1iaUHRfxXDnjPeYXViG8s+68clcEeiiu99CBF/og6XFegL9tRpn4WxKjLg7IWfw7UmrYB+y9S9L3fFZ8r1UlHJosaNCc2F+o=,iv:llAaylrVgAh4Jtfklern2pIOimPrOzUh7asSCpbnDcI=,tag:w8oY4lCQsEz61ACjVeYEoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
