apiVersion: v1
kind: Namespace
metadata:
  name: gptnvd-reference-app
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nai-llm-helm
  namespace: flux-system
spec:
  interval: 15m
  url: https://jesse-gonzalez.github.io/nai-llm-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gptnvd-ref-app
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=gptnvd-reference-app}
  chart:
    spec:
      chart: gptnvd-referenceapp
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: nai-llm-helm
      version: "0.2.7"
  interval: 30m
  timeout: 20m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    frontend:
      enabled: true
      replicaCount: 1

      image:
        repository: "quay.io/wolfgangntnx/frontend"
        pullPolicy: Always

      imagePullSecrets: []
      nameOverride: frontend
      fullnameOverride: ""

      resources:
        requests:
          memory: "3Gi"
          cpu: "1"

      service:
        type: ClusterIP
        port: 8000

      ingress:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: ${cert_manager_issuer_name}
          nginx.ingress.kubernetes.io/proxy-body-size: 500M
        hosts:
        - host: frontend.${wildcard_ingress_subdomain}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: frontend-tld-secret
          hosts:
          - frontend.${wildcard_ingress_subdomain}
    backend:
      enabled: true

      image:
        repository: "quay.io/wolfgangntnx/doc-ingest"
        pullPolicy: Always
        tag: 0.2.7-1

      imagePullSecrets: []
      nameOverride: backend
      fullnameOverride: ""

      resources:
        limits:
          nvidia.com/gpu: "1"

    milvus:
      host: milvus.${management_cluster_ingress_subdomain}
      port: "19530"
      collection: "${documents_objects_bucket_name}"
    inference:
      endpoint: http://nai.llm.${istio_wildcard_ingress_subdomain}
    s3:
      ## need way to handle https use cases
      endpoint: http://${objects_host}
      sslVerify: false
      region: "${objects_region}"
      accessKey: "${objects_access_key}"
      secretKey: "${objects_secret_key}"
      bucket: "${documents_objects_bucket_name}"
    kafka:
      bootstrap: kafka.${management_cluster_ingress_subdomain}
      externalPort: "9096"
