apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: flux-system
spec:
  interval: 4h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=opentelemetry}
  chart:
    spec:
      chart: opentelemetry-operator
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: ${opentelemetry_operator_version}
  interval: 1h
  values:
    admissionWebhooks:
      certManager:
        enabled: false
        autoGenerateCert:
          enabled: true

