inputDir: tmpl/cluster
outputMap: |
  clusters/{{ .Env.K8S_CLUSTER_NAME }}/{{ .in | strings.ReplaceAll ".yaml.tmpl" ".yaml" }}

# plugins:
#   echo:
#     cmd: echo

# context:
#   config: .{{ .Env.K8S_CLUSTER_NAME }}.env.yaml

## this feature not available until 3.12 gomplate, which isn't available yet
# missingKey: default
