version: '3'

#vars:
#  K8S_CLUSTER_NAME: '{{.K8S_CLUSTER_NAME}}'

dotenv: ['configs/_common/.env', '.local/{{.K8S_CLUSTER_NAME}}/.env']

includes:
  helpers: ./.taskfiles/helpers.yaml
  init: ./.taskfiles/init.yaml
  bootstrap: ./.taskfiles/bootstrap.yaml
  kubectl:
    taskfile: ./.taskfiles/kubectl.yaml
    aliases: [k]
  nke: ./.taskfiles/nke.yaml
  flux: ./.taskfiles/flux.yaml
  tofu: ./.taskfiles/tofu.yaml
  sops: ./.taskfiles/sops.yaml
  test: ./test
  workstation: ./.taskfiles/workstation.yaml
  troubleshoot:
    taskfile: ./.taskfiles/troubleshoot.yaml
    aliases: [ts]
  kind: ./.taskfiles/kind.yaml

tasks:

  default:
    silent: true
    cmds:
    - task --summary bootstrap:silent

  print-versions:
    cmds:
    - echo "KSERVE_VERSION=${KSERVE_VERSION}"
    - echo "ISTIO_VERSION=${ISTIO_VERSION}"
    - echo "KNATIVE_SERVING_VERSION=${KNATIVE_SERVING_VERSION}"
    - echo "KNATIVE_ISTIO_VERSION=${KNATIVE_ISTIO_VERSION}"
    - echo "CERT_MANAGER_VERSION=${CERT_MANAGER_VERSION}"
