version: '3'

#vars:
#  K8S_CLUSTER_NAME: '{{.K8S_CLUSTER_NAME}}'

dotenv: ['configs/_common/.env', '.local/{{.K8S_CLUSTER_NAME}}/.env']

includes:
  helpers: ./.taskfiles/helpers.yaml
  init: ./.taskfiles/init.yaml
  bootstrap: ./.taskfiles/bootstrap.yaml
  kubectl:
    taskfile: ./.taskfiles/kubectl.yaml
    aliases: [k]
  nke: ./.taskfiles/nke.yaml
  flux: ./.taskfiles/flux.yaml
  tofu: ./.taskfiles/tofu.yaml
  sops: ./.taskfiles/sops.yaml
  test: ./test
  workstation: ./.taskfiles/workstation.yaml
  troubleshoot:
    taskfile: ./.taskfiles/troubleshoot.yaml
    aliases: [ts]
  kind: ./.taskfiles/kind.yaml
  aws: ./.taskfiles/aws.yaml

tasks:

  default:
    silent: true
    cmds:
    - task --summary bootstrap:silent

  print-versions:
    cmds:
    - env | grep _VERSION

  print-vars:
    cmds:
    - env | grep {{.CLI_ARGS | default "BOOTSTRAP_"}}
    - echo ${GIT_REPO_URL}
    - echo {{ env "$GITHUB_REPO_TEST" }}
    - echo {{ expandenv "$GITHUB_REPO_TEST" }}
    - echo $(basename $(git rev-parse --show-toplevel))
    - echo {{exec "ls"}}
