apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 4h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=cert-manager}
  chart:
    spec:
      chart: cert-manager
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: "1.x"
  interval: 1h
  values:
    installCRDs: true
    prometheus:
      enabled: false

