apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- gpu-operator-repo.yaml
- knative-istio-repo.yaml
- knative-serving-repo.yaml
- knative-eventing-repo.yaml
- kserve-repo.yaml
- nai-helm-repo.yaml
