apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- eventing-crds.yaml
#- eventing-core.yaml
- https://github.com/knative/eventing/releases/download/${knative_eventing_version}/eventing-core.yaml
