kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:v5r5xj3zDRgELApmOmP6L9kZ3RTuhtoMb4dfwdrmLzNU9Zc8ko5W2eZBgF/ZniPsx09yr3I=,iv:sm1Iu7qeMZwKlW0Z521rsfBuky/46YERETWJUU932Ak=,tag:L70ZKdIhvP+K8h/0Nc1Lew==,type:str]
    github_user: ENC[AES256_GCM,data:5fL7xYx+prLV4ahq5rI=,iv:va5fjm3gjQ1PHT4HPInaKKBaD755R7crCAyG4GOWnsE=,tag:uZ8jXlnpVrmRRgbCDmBDQg==,type:str]
    github_api_token: ENC[AES256_GCM,data:FwGwCwKpTWPFo5/BQHEGE0hxsk+k2X+JHZNzISiJx8/wq/d6uSH6Og==,iv:fM85Vche8g6Yo0jSKArQv1+ArQnhio5ov0kQAcEM+pk=,tag:jiImkvJP1kbTSqOMmctHWA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:QDjzGrLKL90=,iv:ZdKXg6fiQcSDItfPN5Z6EQSfIqIh+WhTamOghI8kWTY=,tag:XqK4rIiU3czrA03eR2t7+A==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:rOHcX4b0WLU9CpYDqv+5p6NUdZ+ea4+mZ0Nx2uQuyrRq5Hnf,iv:tXZLgre++aGD2tTGKE0uTlCiWeCrRCGxoSE0ZGASaF0=,tag:cGSjogZ3crJlsEBnrwIb2A==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:ZJhDV6YKHj1QEoCH,iv:IAsBbnSF1a+fDKLagInZh9p1PnnOmvmGIStNVv8/hJ4=,tag:WwiPr68ZmEzXXtJWYvCarg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:mQVx9Zs=,iv:05XP0MpC9F7fA4hNxT2D/00XSws+48wtOlaWmciS9HY=,tag:TNE6/PbtF8s/JWqeFPWQBQ==,type:str]
    prism_central_password: ENC[AES256_GCM,data:B6fstY5F703bIhU=,iv:/tLNBYvajfwDAqXfSIKgMhc/P1FwFlfz5CMHEovv0cg=,tag:ABx6Cd8xbkMQEM3q5LhWXQ==,type:str]
    objects_host: ENC[AES256_GCM,data:txwnSmfZ4WLuuK/T,iv:SuMpfZkRda8rRysuKK5aQkcTIEjaZihpE46zBkX2AlM=,tag:QxZ1AAOemzonyUVqZBcs4A==,type:str]
    objects_port: ENC[AES256_GCM,data:cSc=,iv:p7xXOk4VpN+r7QDR76zrfzbNEMTOukDCep733+sbk08=,tag:uXJfP3eU3f5L9lgIeiBUSQ==,type:str]
    objects_region: ENC[AES256_GCM,data:LdUHWsX2IGyC,iv:QX8aSxMDPCmR8rsMKC+AFNI2dTqgymhaEv5vDsy3Bm4=,tag:CgGRfTX42h3TnB9/HP9PEA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:bfoZiZM=,iv:qBMg2ts3ik8nedq3FREmjCr9TC2jnR3VZ3jOpFdenEI=,tag:4ZoVpIADVKDs0bWWUPZxPQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:GMlRuo/EgWu1pbELef1FOlhiahHT2fYHwsOUfUEo0HI=,iv:182nfLsbh+IpTFYAokxljjXWWExpny4aVf2levGb5fo=,tag:fjQu6k7znP6yYdQGFfWA4w==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:vEpMDv4IEE09F5JnqHrs4u5HVnL0fEopn9K4i6MzEWc=,iv:bP754psNL3w3WaTXYnHIF0yV/icx2RGykNxA6wr2NkQ=,tag:dtT1509godH4v05uqD7VMg==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:qFs8OhE3P8fAoHldR3hDw2H89A65sso=,iv:EE5DdBOv3Rs2koYpb73DJ+ecXHGwYzEBNQQV5Kzp1LE=,tag:LjGlW5l7VxbJgP3pMOBzvw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:8f8BoDmSVbM+ynPK3+o=,iv:eJp9/x5rW4wZ6StuP1fI7U2oWmWM8fmaDyiFk3Y0fqU=,tag:a0boqo/f3zjzuGheL0ximA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:mZY9jHFkrCUJK/AuV/O2ig6p25no+PTrSgbmi9dpSsib,iv:oAerd1dJGjxbArNmlS1UUdSbQP6/7Lumlf8aX2RSUWA=,tag:HEWP84ZJ8cSDfzlrpqqdvA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:Y4qY/ZMwCCECZ4/GD7YepSo46dYW+VUx9A6bUoMDC10E,iv:RV3R14YSvYE86MkvuItTota52xx17lIY+gHp5UGNCjk=,tag:WjcrcEZiBZyunspCKh3nWQ==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:NWA6n3Pl5/QxuVc1GZ1ru6D8,iv:NiedAHyT8JwzeIk1yRTJHfjtkChhd0eZTAzisAB8q2w=,tag:gnK3GyGnGpHsNHsgBtDivQ==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:7GUGYyXiMKrIBeLZ+A==,iv:bjDIgjfvnKC1wib7JuA9gowb103mSzAVTsfTeZbq998=,tag:8RIYcJt9oszi84ob6oQshA==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:6qawKCwYGPnc,iv:fU2YNJ8a6oR//yiqY2K2G8ei9WJ28T0C3OVpMJqwFxM=,tag:V4/wZ7HzO58yzhxcNrbIMg==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:gG40gKawhJQc/Clm6W7SIT5Bqfk=,iv:Ji36NI876SCMuWB1/z+vpMbKr7YHok1BqOA3zHk+coU=,tag:MJp8sdrshkSusyZEXbTF8w==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:SApdZmXPOoMw/Mz3hSNu5Q09JTQ=,iv:Cx2eWqimIMgLgvWt+sXkHEH4YYK0cJMAU31YS6hgofA=,tag:rgvDTIBFR7Ml6bdUju05ow==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:FH1sKyZWEmpCSFG7oiKcr9chwsXrDQ9ZMmlYf9zrXTCbZrqjDXBalg==,iv:6k1qpv8L5Axr/twimh7tgARJVpy4DzS9c3F7LcJeEWM=,tag:OBL/mTLO6IXP4D2dP4v9YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aXQ2cW9wQUJ1anFTbmpo
            MUpTSWt0eU9jYVFhTVAwRjJkV0FFN1Jwb3hrCjRsYTJyZFN6MlVpeVhCQ09MeVFa
            VGtXcSszRDFqbG8vOFBERjN0OVljV3MKLS0tIG1BWFU1ZENZaWFQSjZBamc4WUw4
            dUl4Q3hmK2kyYXIyZWJlb2xNNTc4c00KP78vb1uev5dzbJsrOincvOMmQzreDoKS
            7QLfH+ItVMhsU7E1QowJ0l445UyHRIeLywTj+bErRBnzuMOehkmCkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T19:15:43Z"
    mac: ENC[AES256_GCM,data:IqeHbde0IQiY6DKxDGfDmwdHafnmK0205//qZevft2IHU4/y6/zXccQe9XahVl972KNZqx2u8WJiE1rCYj2/WzeE4c/cC5fe1msAMZ7prfLWOVNEXYr8lFq2rkPnlhfzO0CJmKR3Ttgj6zmEdBRozUsMGuTrdSdIKyw36rBdGj4=,iv:L3uYwB889j4G4Hqsbgmt3NNREufRvOctfvwQp+vcpp4=,tag:/GZYt57mLWuKkGocovGKUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
