kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:yVepRbVm03/mjKTs8RuRWVkrcJMYd1s3mT8Mys/lL5s2HvsVmv0ENg1ikVBKpn6tLATbvpE=,iv:ZXJBHHqx5WfxcEU3aCYh8FWclSBQQFpMZQX4WO5lvsY=,tag:V7dE6Yi1X3nWUetbguG0yQ==,type:str]
    github_user: ENC[AES256_GCM,data:zj0guKvbCDQ+VenRsq8=,iv:9tw2vlqmmCU3hB2DTod1RSg7jr0wwYJA659PJZh7Vm4=,tag:C41mKFodlfsUG9XQ7RzGTQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:eFA/gCiAsgmHxnesKnyFKoxG2XCLqZG02FZvIR3+0RXldtJwU3kAnA==,iv:5nT4O8F1NSnEJ9MPu01yRjWTSflqsfafin2KWtW+R8M=,tag:fFxuOSQorBCls0zHDfBgdg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:akZyrb+EWzs=,iv:scuqik9jGYxvjcxm4uiRyipS6FiaTiKltVDetHkV5HQ=,tag:LyfnvmpkKHAuKeRiqwWk5g==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:JvKhLYZQJn2Dk7KcvpFDvL2/8RBUBJ4otosxn+CUEiTBgqo4,iv:fqUcKvK4zA4cnwz3KYprKL+ingz5eUlO/eMN+ByOtck=,tag:1RmwvqQBx+NZM2Jw5S46/w==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:E+XGNvZVjlfLmQxB,iv:mQ0SAVwEc2H4X9rWDXnZ2R+dFlKDFGz4A1363MAK7qo=,tag:tqifqE9k4IB+yLxiZBsqmw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:r5l5/5g=,iv:y9AoqNQJ6nQI2dvTYd/vAxthXzosNthOVkfOSdtUWyg=,tag:KVJskz4T5kF0zT7/MlZk3Q==,type:str]
    prism_central_password: ENC[AES256_GCM,data:SyNvxrzaavwrtLE=,iv:vmZ6hRX2B+g59uJFY/C7kRgFAgRi2XpfzZBQc/f8V5s=,tag:ghGFEtGLfpPIQML7geWwBw==,type:str]
    objects_host: ENC[AES256_GCM,data:IEXiSJjoWSZA7G1M,iv:5CTPKdtYRoYOUsMGxdK6u0HoPpvRulSti5CHG38O+BY=,tag:7V2oXYMg/zG5LfLoLKGNXw==,type:str]
    objects_port: ENC[AES256_GCM,data:LTc=,iv:jy1uFw9IADmmqiTXzj6cju/5Yd/MomRulz3trZ6ZJ04=,tag:FNfd8lwsY7j7k5rtfBp3ng==,type:str]
    objects_region: ENC[AES256_GCM,data:8MYtt9da0kFT,iv:ApX/CYi++k+ctu7KEJuwK56ky3QodTM2XazZFKLV7Cg=,tag:efl3VWxe5U+buxRp08LM0g==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:F+iyiHA=,iv:Y0Vtijz29/LYtgSvXiV0wtlTHf4L8nIr8qifQ422EKs=,tag:++Q8ktYI2yGJbO7Oq/eTfQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:bhn3+ZsCex/JDzN9081nxIj5IMebHqH1RCcFS1bkH0U=,iv:lKe2iyY7T0a//+cAM7FV2ObuCaSN0mnVwbTw/VTOLlw=,tag:Jpmawu3xJHrs0Nq/Oi8Rzg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:fWiaOxQJWqWKU6tYjG6WuQbkQAj6UbefiZsRKyapIDI=,iv:S1QwP54NQJ97lN8ctpWQ9aGV2dzaIX/rGLCFzsMu2CE=,tag:/JRRKEiXW1SlUZus//fIGA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:zbJgSdUVYbec9zm48oX6iDc+gMvxsTA=,iv:fCMytV8Le57C7G048QcIkO59BN+Hj+Q8fABqFubkEAM=,tag:z+zlJc50GeV8IPOJHOK9Pw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:nyEwuLW//jDrQC2wJRk=,iv:Ax4zjb31CmB5fX78wY4FOe0cI1CWX37a0aCl2UMrxKQ=,tag:vTP4/uwqeLsWFdhyGQm+Mg==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:+XGY3Fgl3WpeD2aiDXe1gNqBGkuhg67kmqc5RP1fKlDD,iv:VAFZUA7KdOHEYQzTKG5NBCt0uLqY90mvvZseVSHA+/U=,tag:+diqJAM+CkmzzFkJil3XRQ==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:y3cwEw3RyV0A6W55anPov9dH2WyPR9gc4oTlmdkZWu8l,iv:StIQHP9A1kUv41WuOZ+mea9v/ZQU00J6wVcAZdxqmB0=,tag:Ym3715RZtsB0QH1/VO+spw==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:zIblQ0okhpQxk3qnU8AcLdrT,iv:GbqbAe7oboaUMH6QScwwQKh9i+a/CYdME5rCXD+TD1k=,tag:OUdwc6gaLSnNfYmZixgo8A==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:UmNxyZvz8Sxc9UtwrQ==,iv:dnJG4jlP5eMjCpkH1ITIllaTINAjkumNp2LNrLX4zao=,tag:YxHYdErJQ55spa2r8Z7QEg==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:VRY5VIhIroBz,iv:G8a+7Jw8p6xEK1vy4JZWB52ZR0vahInQeU4y7KuWI/M=,tag:G8f9pN5nZyFkJ0mvoEdHuA==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:Q6ytSlCd2eNfzQcl/tPrFrvcpBk=,iv:BLQQXQRrNhS8zncrK0y/6ewUQE4PXiAnC/ZsIEyKGVU=,tag:14YQkV/Fo6Q7M7BYfTF9rQ==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:96VJd37x4aonxrepabPZx3BOAu0=,iv:36SiodSipP1m2Bz6CCELduhDqmSnkNLmzXUPv53XDnI=,tag:/sj/T0uHET1VBWalW/rjqQ==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:e1xW4YzyW05f13fmKmzGejDMBOGd8SsiUGsZMvOFNWA3gVTozCL9jw==,iv:1ya1cboXXFdgY5VewcJ2JqVLi6bkWUyQRRUUqZfibWg=,tag:2bsir7SvdXAeZOfVLnAnYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQnBlWXRQSkNBNEVwdDhk
            Smt0UVFtQkhJa1hhS2tVK2dIcGxLYnBHbzA0Cm44SnVqLzJwZ2pwNG9mUWRjMi9O
            TGYrWlpmWnpFclFMQ3RDVUNwbHIweWMKLS0tIE56aU03bjUxSW1VeExzK2NoMmtG
            MGN5dGplbUtGdXp1OUtNQmpEcExQYk0KAl8T5l3xids5v/dgJAjGzYp2yGY794Jk
            8lqybz+jcv6YQVJmK/U0bYwkOK/eQE0m40CMouMalcmWGluc18p4Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T05:40:33Z"
    mac: ENC[AES256_GCM,data:KjemAuCqlUxO3zkSI7aUw+8acvg/g6+uWBe6dk/64RYf0CzF0jz4Tn6MiXautBHdNtEMtkcmHX2PwEVxY9ysQb6pBv7tMEEbPLFkQ+5Y2nR/r3Qwtcy1U/uJXOwX7D33iaFoPvrz4XXYCtgJmcU+7DhYKrQPllVSjva9BUSKgDE=,iv:B2g+insaPTkTsuoL1P4dQuSSO3z8KrIRPg/qSCWRifk=,tag:5jpT6/qMu2meixqtmnJJiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
