kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:Z1Feq87QcHctqBvgVM03/HLFl3h6gEukHMK6k5EuCFCTuKlRLHeZ1qKPwzZWZmat+p8+Hgs=,iv:M9cyFdMuD5Y61sA294bPKnE725Cu5vYVN7nvinDw/Yk=,tag:22i0I/IgxRqKt/Whwz2A1w==,type:str]
    github_user: ENC[AES256_GCM,data:726xfBCGU/Y3bijC6vI=,iv:0JJPJQsdV9rq/WIdJDtw4aYc7Onfwm56fn/tByltO8c=,tag:noTCHk16jMw8vZqpL/R5lw==,type:str]
    github_api_token: ENC[AES256_GCM,data:MF4Gb7EroTJjfSvyN1/6ik7u263WWvVnUX4pSrw+IIwcJIUYRbO88w==,iv:/8LF//1tyS1fpIy2Q2V01Ul1YUPwK06GTwtiwA7WCSA=,tag:PhltmvpGLM9XK8WAcyyAXg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:Fhq5f4iD1N0=,iv:vAEhJ0hg7/Ur3re/Pj0r3KLTUsRIpk9+eHbrLGv/nSE=,tag:DsldwK20rmnshdSJ7hjJGQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:kjel1a6fE1pAL437sGz2H2l2Gn8YwNF3L6eMCOPDORBNBbKN,iv:8619dk5PScXTs6XElaAAkZQuKdvHd4eaO783Aa9i50w=,tag:GLRkK9EEdq9aym0oqvP4/g==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:rK+DfhVDEycaPZ0A,iv:6Y/a8vc4tpKQ08jBg6gTKeti81sLQJ3/2qGnRYBhuRw=,tag:YrBEx4HX1WbfJ1rFQ47iqg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:pjP8zF0=,iv:XJRxXEap4JRtj3Vs+jrrotVDJZSB8+bLaMTrNBUUNT8=,tag:QlVJz2GXqeiI0C5FTS0Q+g==,type:str]
    prism_central_password: ENC[AES256_GCM,data:FSLbFU1iCpDFn9s=,iv:obkYptJ8C+tSZLSypWOJsg5DyjagL9jVQCDG6ndMI58=,tag:w3Da8Cr4RdWb0cjkxpvrng==,type:str]
    objects_host: ENC[AES256_GCM,data:V+Ag7xc3aitJGPDl,iv:YsrpD2ELj1GpYgiW1A5qroKHV854H2kuSSlWRmRHzFk=,tag:85PmlURMxl0scXsyZrLakw==,type:str]
    objects_port: ENC[AES256_GCM,data:PtY=,iv:jeZy5yzqUQzkNRn2cFO0gIOrsHYukHaxvCU8g902qog=,tag:TsGTkFduaqpA+T9/7CnRuA==,type:str]
    objects_region: ENC[AES256_GCM,data:t+lcPl/Nrvqu,iv:B4qwV3ZY9x+FHRhzJuD/M0g3PPjYLrMBHDC5WLi/kXM=,tag:6sx/vqWsZ30dvbHhDO3WlA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:JVRLKLI=,iv:5KK+UTCRMwZ2MbmxvHAVgDgydUxRF+RCAhCpmIg200s=,tag:22Kb+EMAWd2gDKFQa/hVxQ==,type:str]
    objects_access_key: ENC[AES256_GCM,data:37v4nxfpbMrYEjV/meZRvQwAJ2e6Q2N3EG8pM/viA/s=,iv:UodaBj/z172GRjAGc9qg5HEVP+Xv6npTegurUky7TSs=,tag:52DDACAVFxWfA/qmltXsyw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:5v3LHseohG4SsTvTT5JLmZ+vTTuu8cOdR2IpS3JdMXA=,iv:M4oLNCQEhi4ymtptHPHfuUfBZO0Ghw7t0VAHbx4e8IM=,tag:A8DAO37KDQHJIT2R+76lwQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:tuYYR6UCNvMnaMHxHaTmrENF+voJ8Ao=,iv:p6AxJx6C672u75uGHOV9cCzAepXdJM3DgjwzWFF/D9I=,tag:hblQmg+zyeHvze9MHErqEw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:fhlBFhX95N6E47gyg90=,iv:uGLwwB9bgV9BZV5KkKpf4SN55PtQrO2nfdVH4dxpPfY=,tag:Gke2YIPYegg0ov9MsmvzqA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:9GX4yextyu9vnjHwOrIuz7tBJyH4iafz5L5BLKcMpEIE,iv:nCnP6BekznpDamvkhCwuohL2W91gycvECd0JP5bHVrI=,tag:xUGQ03fM5LUzBSHpT1rURA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:i/XpoaQdEEaUgr3MxByd8nIDr6+D4LEDAm279P/Wfj7d,iv:db2x6HIEM9jRhV6jPBsplk6jBjGaqOuR588BojrZzxA=,tag:Wi2HYp1fgE83cIaCE7TMZA==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:6i037CfVfk9e2v3zCLXFLUJ7,iv:/gqDqIGu50u05Jwy0ZoptVzLVvtSLW/2RTLOsr7JAFI=,tag:CXXda2i7B8bUha3W3xgPAA==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:hM3WPFrWNSx9IpgQfg==,iv:Qct5lgZ8W0UEAmyIHsY51/iylOimmN3oiDU6IRETXZI=,tag:nR/OwbQCjeUHtWmtEfr5AQ==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:Q8lx+Rcn6hgW,iv:GRwKHDcJ+KslEra/cggnACF0T+lffZi9FOnjOwALoJI=,tag:nxpbBTl3QYVU1rGHaYHR/g==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:O50Le7tApzkPOWaZ8bO/cCwQy7E=,iv:GdYJj/pixa3SXt1ksBlnOfArBnQLrPw36jsp8xls3EQ=,tag:UkvCOaI9YrXp8StZ5CF3zQ==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:JudvwEc5z3tOZN+oN6u9h+c1S28=,iv:fTYvve5aNpcURthhvgkh7L5oYsptwnQRpOK0LIWnIsU=,tag:kRXPMs0duie/YGBNRDv0zw==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:VF9AcPJMWP4hcsn19rWrRDkgIUWKLCR9LF2nuYL5+k2L/l4sCVzw+A==,iv:8K/Cs6/Dul/uon6MO6vxuhDL/f8wjKSft6zCGPHsu9Y=,tag:oNH6XN6h+x20hRsOsL3OFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQU9admIzNEFKM1JTOVBJ
            WEw1bW9tUkgwMHlzK0hCekVpZVZQaG9VUG1NClh0SmlMcE5vYkJESDZFY3JOYnNq
            KzhKQkVFWUtwaHc4eWE3T1dRcXYzWWcKLS0tIHhyZFhmL1UzWEpYYTJxeUNYR1Qy
            R0RnaHRhbDdxMVRvMU81djFjVnVJcEUKqvW37fQ4KHgjA7BTMiHKotLT7XDcX0qU
            wsXj8DzqOw27xzA9Q1f4GBbKIae1E531bBkV/UZcR3pu5sv3RuvTzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T06:05:26Z"
    mac: ENC[AES256_GCM,data:o7/BueyTcVxHLcIl9dwivXa5UfFP7yOXo/uow5G/wVOYmIgbHl/ikpa8KzG9L5x9P+MNvgPQBRoLx/cWEBRzb7gbGCn2MnawViaRMjsX2TnudrCb9zuQglb7Drhi3IF1gW4VvYK8QzsZ3eJ82+SD3Yxb9n7m8Ca4GSwVqsYBkbc=,iv:3eg78dxHG+L7iUk+LxMX767EWoX28YtK4+3ELBrq3u0=,tag:hN/rEZeoCszWODtlWP6JtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
