apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gptnvd-reference-app
  namespace: flux-system
spec:
  dependsOn:
  - name: kserve-post-deploy
  - name: gpu-operator
  - name: nai-helm
  interval: 15m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/gptnvd-reference-app/_base
  prune: true
  wait: true
  timeout: 15m
  postBuild:
    substitute:
      namespace_name: gptnvd-reference-app
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false
