kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:TGxke4tZbeElPxjBxlmB5ilx4Y1aMya9hZM+rozTRT8grLMB9PwLrdlVX4YzyYAogaELIxQ=,iv:IOJER20AsU+ETuGeScpwb4q4EYwFnNkRLvYHu0Og4i4=,tag:IQ1uI5FT+QvMkNIRJ6nfbg==,type:str]
    github_user: ENC[AES256_GCM,data:ZGJ5EvhhhIuG8Cjg1sQ=,iv:NtdJLiJFqAOK6VaqKouFOTvZtQbd5h8lZEaYIvQQUZM=,tag:vdZP9DLULRcuvuEBcujH4Q==,type:str]
    github_api_token: ENC[AES256_GCM,data:frDK2FP6t25f9wl1S0anZVGwoYl1fpfNJsSW40NBfnzlGskW0APcvw==,iv:Xk2wjW6RLOB1W76wJZ6Ag42jDad5sNqDpqTIVkakGYw=,tag:0pVZS8CjDLx/AWXIsA2vVA==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:JpVp/PP4pkU=,iv:EKfkfsnTlYgg4W2dFpWg3HSt8fNlGzEXuVJdaGh0B3M=,tag:NDPJbWdCvTKCyvZUPqZtbQ==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:lXc23yX1+OwSy7qGBehCp551bqEL3AGnH+ri5tjA8s3519Tp,iv:FLICy/+EBJRZMibv2o76cjh2yGdEpyoV3le6RIW1o0g=,tag:aK3nhh1+oTP8jAapmP+m9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNW5FcmFmditBOVRBSjA0
            MWFRb0R1RDZFWVE2QVpuWVRkWDlWR0VmMEJRCnJJUmtOd0h0dm8vSDNVOWp3bnY0
            VkhmSEd5R1BlaHpGWTFYQldhYlFhbGMKLS0tIDRLR1RGQXVxREFRdkdKZ3QrME9y
            dmpHK2Qyd0REclN3UURnN0FBY29nWjQKJTfVmQvp0iN+z0h3vyVrqX59wxc7KO1D
            IrYiQIS8oNVSQEws23jM5Gu+0L3VSnWNQJsvmUBaOU7NAkrIG649Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T00:07:20Z"
    mac: ENC[AES256_GCM,data:5TjhLco7cKpFPz45WecqsRHO/esgXMjl8DmSBIxgF4qOBmIqJqdPfYHllCrWGKUI5dGyJaUOfVBgwiL8X1CKbHZSIRtzUP8EE7uF4KIk0k8T47H/uWCiA4BgVBZfYiokdupbc7gDbwD93LHyvBUFcxHno8FnlO3UivZXWZ86gj0=,iv:xowqJsEeWDB5tvPXvnrCvkjOQMTA6FklKTaD069hbvo=,tag:5f59/LyMKRqucRFJb8Fg3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
