kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:D/7YMtGtwjlN9ubBbp2b6l5GGaPk89WswP6GwQL9ICirBx3PzBagvP1wH5tobvIWqf6t8Vk=,iv:r1vJQnjTbGg6RTi7fvUw25XnaVU0u1x5GE4JmhFHQpk=,tag:qHQqfcQmP1N2uWkmahnoNg==,type:str]
    github_user: ENC[AES256_GCM,data:sD/yp9dzChvLmEilylU=,iv:znIBcXs3z4RQAp2NbJ/bHJ2EBjaIiI4tOfNQrjZuxgE=,tag:cLGSnQLZ6Q72hrFjjm2Q6A==,type:str]
    github_api_token: ENC[AES256_GCM,data:1MkIvRoFSf0Sz8tmW0QW5G8kCvH508E7waWVdZBhxLBZdXSHZTcezg==,iv:1n02IJSRE/1MLfzvyjKplDdWNc6ztFAuKPeuf7NkAtQ=,tag:eCowSXC/he28Z0IPPSBwEw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:/HlB+r18Pyo=,iv:PloyRoochlFHMm7qgGF8TimQLRINUKs8jAbf/UMLSDc=,tag:zt8Qej1S1ELbfx0cpNlGwA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:XYF/8ZFfsaAJUGWNBYegW07TBtbZvv+TLz3a9hmvjsEcm2jv,iv:/5biAM9ShKUb3IyAM221Fpj3ubBvRbEXXjSkRxPmoiA=,tag:rKSPgAOKUqFpbKmYO1kbLQ==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:V8sC9Q0BtMEzXmCK,iv:6P4wFFRWbNBQLf+fdj3adaKy2f2/hZm0WJ1mCLdveOQ=,tag:cH4iyi3OQDZvx9jGrm952w==,type:str]
    prism_central_user: ENC[AES256_GCM,data:hOBUymc=,iv:MkcPIFg1SVlAx6fKHMpi6M5HbVd/AWqmBq2f4BdQYY4=,tag:xe9zV09wR8lU4NEi/fsyrg==,type:str]
    prism_central_password: ENC[AES256_GCM,data:V4MIKtM1QGdVGsg=,iv:0B5cm4GGhjFV8SdLikNZkx0rapBPRnqlGCb/J+MrpT4=,tag:FpBqLfbKt8OS16qTMtxv9Q==,type:str]
    objects_access_key: ENC[AES256_GCM,data:TwplflgtT91RKwHBY5GPgapzKTmfWD2R54VE2OuC5ao=,iv:1JLyghcRiDxxCUnf2atr9LMEgbN/p4fPpbBxgLmbRhI=,tag:iCz9IB9G++pdGqLnfTqpEg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:iokqmYzDYD4BMLxzFgGOxokjofIyXo9WftlG9jk/jZ4=,iv:F1C9R4VnLiEn/qG/kZEUxHS5fQX+3UUqrnDJxBKfPbo=,tag:QlPQXSpPegGbPiWBAoniIg==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:vggmRNL3g/wjOWHCMpe3AiRVtSE=,iv:qBRazkGd8P1HQWRfWdp2psvqCutKw8vgngNjUGeEJPs=,tag:bjCLh826ftWuJHKPHKDXbg==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:bfbCj5XW7yk0hS/WZxc7edeh/QdrIxSy+WKkjdUPFJGhIo1UJEe1aQ==,iv:Vm2SNp/nFf2k2b5Rqc1YQSXwSoeNecWTQDt8kL1aI+Q=,tag:359L+ioy5ZBeM4oFt+QnQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU2pDNWpwNFBUMzVhYjhr
            cFgxSlA0alRuYTRPSk96MmF3L3gyUnV0VTJFCm5ad2FGL2V5YVAzbGVmUHo3M2lu
            OEFVWmYranV0MTFlWVppakQvemdJSTgKLS0tIDhMbEQ5YTd3dldSeC96NFl4b2pR
            aGFaZWlLVFZxRk9TL2lEZnQ4bm1qT3cKP8SrvoDAU/0eZvMorNENpKg144OPennG
            +ifBPQXX8h/5IR698uGbZqSQODFVUn7E5mNme/S8k1rrD45hbI+OFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-17T14:44:40Z"
    mac: ENC[AES256_GCM,data:bVGagzd+OV3ceEEw8b7mbSay0M9fYVDL0jrfmTXEQibMTQX38UbeLPuMoePU6yF3ZCqzw7CGqY1ERQNRl7jXx1fpy06FYy9RCuV8gdeXD183jKFGaGvKNYNlcXfECqoRkltOgo79pbGCWwrKS3aM+QYd/9WLrmmA2toBwxy05UU=,iv:1lKODN+x6FPdwr0S+LLGGR+Mltlj6nkFnwddduebkJU=,tag:2Q1+ggqe6aXFey8pPlO2LA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
