kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:B5coWLMZjiFucPl4z6vW+SJDpjSs/cjmYA1L+jzhL83RoJvvYSh/pXfN3XEFKYWXnc6dzm8=,iv:hz1BOCOopfCSXuYh4DpYOKRHd9dIaD4uJ28a4cxvOL8=,tag:wHkvKbXdQX+rC2kceghO0A==,type:str]
    github_user: ENC[AES256_GCM,data:Oeb7PrkFfaKwGL0sz0E=,iv:i8nSlP0NW3Zf8GFQytRCpM8KfIlN6V2zbAuHyB4/JvQ=,tag:SJ01YKqoPIii4LwoqS1KNw==,type:str]
    github_api_token: ENC[AES256_GCM,data:nJnmQ4NCGHZ51EIzWmo74exDtMuqB0zEt6fpq0hCoMSm1l6BFj1DiA==,iv:FeTeaCPj8EMMou2xY+Y2AaX08sLBSitqhZmsxuOTI7c=,tag:xi0txbL0SskPjWEq47O7rg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:haEQcK1uwLo=,iv:i5MrhF8ym6Y0hVQVuGDSvWOnV0T+aG8KguSFw/JfFx0=,tag:pEibvPFbm4AGStsT13KiOA==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:Hn+z5B34FKehwgg9JmKN25infa+CLLXWsiYgqAdv3SB/vI15,iv:XaXqPLyT1hYbY9Y4Sc9qb6y374MZqwA0WNEjM1SdfWY=,tag:vPqIg2aladEOmp85bWI5ow==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:VIclD4ZZxHXOVpUg,iv:qCEEJNCWf+bcnJNypLveL4J6Rl4/MvUdP68uHgF90sU=,tag:YC/Y1hfraBrv6VTWJGmOhw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:VO1Lbxg=,iv:kghy4jBcX7Bng0eLq55GMm4iHKRsZAx9HXPCS3nivPY=,tag:z5kqBK1vHB1pv+ijYrjlLw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:BfavYMvjnEkDuzE=,iv:PiIbHoAOJ/bKrPxCy8CE37jfma7H6Fm3UrccnWIfJOY=,tag:TIWozTQfovvoN0Abz6U/pg==,type:str]
    objects_host: ENC[AES256_GCM,data:VGIwZyllWN9xPOxg,iv:aeSMgN2mkSlHU3zFPhDHZ4fRh6CAo9rvmjX//PKAmi0=,tag:jmJoMtNsMVoxQWniFFKOFw==,type:str]
    objects_port: ENC[AES256_GCM,data:sH4=,iv:KjOhviyAIqPP94AeznXb2ODttw0S3Nw98NcjwfQf1fo=,tag:Dx6sjWLOAZIbnzr7MUzAxA==,type:str]
    objects_region: ENC[AES256_GCM,data:vBVqsjBj+IPt,iv:i6/FSK2/xzeD1tch1VuuGzgxwsCHTRD3uNg5g6+Q6+8=,tag:yV+gjnFam5wdTJJAZYrOMQ==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:Sqx/57Y=,iv:BPl3Q2XaerSMDuFYFWXmB9jzWXFkF3vHZkgnE/2p4F0=,tag:1hTbsU9PQ2CSqwj9F2Cyng==,type:str]
    objects_access_key: ENC[AES256_GCM,data:bxD6AdfS89CKLEWEfrZ1glNf47YyvKc7Ve5y9M2AFpk=,iv:dGgrufPa5ZSmBXqSUfyg/jwfn6lRFcHqIA5DbbQb1gI=,tag:hwy6IlYKhSsePGEX56PuVg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:VsX8H6bBPGEnzv64IHO6VtvMw3bIjM2EhRnV1Q/88XY=,iv:ieVCK7jjcGdtXwKfYbig36yuMoVr1NZSDAJoHq+e964=,tag:V/VX0/OirYnfzehXbr8HWQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:KIBI0momcA2VFjYELxzY0w62vuIdwIsGDg==,iv:GzjgFaOw2VFafZL0Tk9M3GL/MmbdxmYXbhdYjtaLh0M=,tag:NKblWZFYNt9YSlvMX8+ugg==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:ABmxADtp5WkXee2FeWg=,iv:9UkI1c32Jv7YItzOH3YPOg5ENcNveH10DttRveZN88g=,tag:Padqh3tMxe7CHKhDJLvYtw==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:I9lye2ZqRS5IgROI2F1BfTMpfQ+bP4pdAGKNWGJVpGUt,iv:pRqkGwR6kB1Rj33fThZENa0556HZ3SFClZBKaNPZgJw=,tag:5KHjgvHx9Sqfijb1h5I7fw==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:WGsBPoMn//+cP+ig+lya493Z1V25h3VBMLVDVI/cV9Ya,iv:N401/ohwTd+VeCTrytS7wFg65UfFJcWp/qcPAFqA8Xc=,tag:fD9rzsm5YHT/CfpAsyfJHQ==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:X0yeaTdwDGckGvCCeA==,iv:iNOx/DnfFkajV+UOirlIRk4lbHV4khbdoJKeWrqy2YM=,tag:U5FoMe3ztf1P4G24eXhLNg==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:K1xhscUQL6Jmn97ZrXw9S2220MuB/UxDpyYVrb40YaS8Moc/qQ==,iv:G2/o3vWMe7nhB6gFmIq/wEHtrynkUdPPEE2Vlt25BQ8=,tag:iJKxd0ASIB1kmjEzmhd2YA==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:8xqYjWqFD5be09zhqw0Zc1ZZ,iv:sWWKsYQ4SzI+WeeM1zq0yxCVVG0u/hEHzdxrJHP31zs=,tag:E+RxDPYJI8j3ww+HI367jw==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:YYN+3kTeziJaS1mZkg==,iv:7WeG6hYTfB8xexWFJbCZa0Myr8Cjhs9cjGkqHDPg0sQ=,tag:YKTePaVNdHpfF8Mzx7dJCg==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:6zZdsg0brwu/,iv:18psCJ33TNEvwAHZ485rPnH+ajVExuhnEwlbE6vxdk0=,tag:LTwBlOYa1cDkb+c0O9EKcg==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:tefyXUEUYEIz+eIDe/fcx07Rwe8=,iv:Qeliky5QUvKWwf6ZYjB3S6o/3/VA7XxTceKxhm6CyQs=,tag:J6/8wd2bbCLiHKpwT3hbew==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:8s0QyNrSh3GjTuAayOWEZ1cpvTE=,iv:Wh8IGtG4e9vm2kYZV4dV1KuhiYIkIdXbJ0J9wqryHGE=,tag:JbrzsKTp+G9sMOTuxaIF+g==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:4s7D7dsYMNbnBKKS75ZbMmdoisnGf9Smtfo/WuuGsPC87fy7FZPseQ==,iv:IopwnWYW+jtGbZYoTsSh5B9+wQgZqhbCR289KubMrIs=,tag:ch86wASUQiXwdYKIWZIvNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR01pU2htZjY5WU51Y3JK
            NW16WDUvbSs4ellFVzdmOG5pRFo0TGxRbWk0Ck9jQ2lHRU9uNi9IejgvakRZTElQ
            bXN6U0VWUFJTRjcraUtZbXZJQ1lud28KLS0tIEIwendHZW1oaFBRY3hUVy9xOXRv
            Y2NXaGxQekk2TGdqbjkwL2dKd09yZk0KYTV8XeQD+A3I/CA1gTIMLqx3dXg4rG6Z
            hwMYKDAm2YcaVZiva4Sf5L8fLZGYJwxof4wsdbofsvl1O/t9de4NWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T21:16:22Z"
    mac: ENC[AES256_GCM,data:wc2mNBdlJM2qfVy/n4HXD3hv26D1vL+h6CTvpW08LR3UtywAHZYrSkSRFMFNc094BPK38XnCKVxW9UdgKVB+BlhuiVRbxxNpywxXUexxJRNOZwaQHVX/ZdUkFJHvc9mVZHpnkUUKbz6zYo3JIsFxudf420cFzcgHiPKoIN2ewpw=,iv:Ivks9zd/TrJQHDw6wTSsrAsscjDzIGw2lTvOAgjtUy4=,tag:YzJwjT5/nSG1MB2/1KiHZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
