kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:G2EXE6xoJzlEEa0WlQI7AzJq2IaHZFBH3adOocPC9isdkaL4qiINUnA7IaCONarMtdmjTvg=,iv:kNbKRjZ54iTIdUvVVcehxkJxHy1u17wHxsnUgQjPG/o=,tag:+Iio7oNMlMUvZoKjvHkJRA==,type:str]
    github_user: ENC[AES256_GCM,data:plcxZJ2lAS0PCgaGkuk=,iv:npBGcG3O+31pKdbMHwVze3pCMUsUJ1eVT1eGM4a4uwY=,tag:7mvhrd4jP0HxkUyhQdBHBQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:dg5SZ/tAzChEAp+7Fpiv+wA5ou0MBGEvgJC543lzKn6U+8518wEEow==,iv:+d0xBn2Du1zSgjFSJGiCDAR9rOv4AdwDloe+gYXjJDY=,tag:ygWBIY3U5WQTL3sjg7eV2Q==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:BcmfxvGirdI=,iv:ED177FDyJpzdICRYEBrlHwDQc4M4r7KguafrhboPp6o=,tag:brZFTHUcxZfGgqMxoNrZVg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:d6/qlS0PxXy2JVoH7ZERG48A/JSGtfV/3DuI6hd989FPT4aX,iv:fnKAoDyPeRTTxrEjhiNTVejDgENacsEr7A3Q3pn/OHg=,tag:h9E4P/W4d16ItMjTcbaLiQ==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:EO+f1fuZyhPn0Z3Z,iv:PrZcpkDyfVy1j6Jv4VuRTo4DsTdhBxeGSEg1SDSkw0M=,tag:Vxal1Q5DOYYWfz4CoojjrQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:JLTbluM=,iv:bzIOFQyeDM6bPFS1J7p3DoINjYrVPCo+jrPVAwyRON4=,tag:B+l4+vONN/x7GmjuZsstEw==,type:str]
    prism_central_password: ENC[AES256_GCM,data:cWOFAIRk2MiuhQ8=,iv:i7LT7qEzB19lcTDb+cJkbytpBe2f6Duo1Sw5Idsk6I4=,tag:FbtUVHlqUEkxAS3BddTBAA==,type:str]
    objects_host: ENC[AES256_GCM,data:SiQMcKMCp7UcgqGE,iv:xXjX1wsKh1614OHItCiDtf4/fWD2KjW07aWOFZAauhM=,tag:Vokv0yJrl0opkVo7mqcQ3A==,type:str]
    objects_port: ENC[AES256_GCM,data:58w=,iv:olfP0dAADMioFQfNRyDHTskhbBA1d4/uhkDEIFXQ9Z0=,tag:PuN717XUE5Si2pq0Dg1mHA==,type:str]
    objects_region: ENC[AES256_GCM,data:Mu6Vh4iOyPG7,iv:toVMRU4uxBFHqS8lzdA71C8GoydvDFOlIEkQ92ZGVRQ=,tag:d7qjEob9mfmYNktIZscXPg==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:lraNWZk=,iv:+ts1YZ3nRrmlD/7e2rK7mXFd7Kxs0uSEIc/k5l7f6u4=,tag:KZOX8YXN3y3IciFVJQUV8g==,type:str]
    objects_access_key: ENC[AES256_GCM,data:X4Lkx7RLfNGbDDFvvaexCRnu8/bE2ajiXLb/0g56P1c=,iv:kztel9p2y57Bo+bn3pXmcAwVudyws+BFjrLN/5pfn8s=,tag:TqvxwlztdQhWZn1gQQ5emw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:ftP2dgsR0s6++mWSBJ+/j8dza524IlNsYYBtWf+nA+0=,iv:lGN+IBKHXvtTIfaD5Z4J+85CxZsKvd+fo4ORk3DbxdY=,tag:M8M2KaZy3mcr2os+MCGDow==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:56oa+iuuDhEG6wJGbErSeQm+Sxddqv8xMQ==,iv:+l5rMQ9Gfu3nf2rIz/WuWS7XYGlO5J2e1Uk8/m6YKc4=,tag:adAc8MBDtuWIAUpjDuHhBw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:ii3t+dcGJRHnSoDNfXM=,iv:YEJeSKdTkRw0hfoUrnz0snOMvZY196z6MMBx1P5DDHU=,tag:JxkBh5FI4XcVe7YzhLzL8w==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:U1LVSGDVMyx74VpHt9WBPK11JuGMZF6XorB8ZbeK1oDG,iv:kShgDNH9fUATlOKEE0SenODTKo5ojwGcpCgbFjhMKY8=,tag:BYpkEupE5iK17aA2H/tlfA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:dk3sCFuUgkD5n6L/GI7BKJCGiP6vyYyHQQyLB14IwXfY,iv:pw9Zh1HgtwQEW1x8ksTD7Jg67rZojR+GwToXiJv2Ew4=,tag:oWtqq6tHdr2ok26XK5ccmA==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:b5lTnR4UAA58pXWZSw==,iv:EGDGE570Jg3y9J6eFBMCGhuFUmYCtdpvy6eNK+/p/W8=,tag:rNMGVkIepbZd+JzAux+o6Q==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:Rhlg/wbi7BkvWY7LuJ7yw/yWmpizDoKGuNw7LrwBZlyZH8qPew==,iv:4WX5HWLl5Uj5LKvvJljArh99mbdG8LA/nnBrlP3U8bo=,tag:0qOvn9pzb1XyOZK8kqel3w==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:D8ctQtH9xhSQvMuhCrI2az0w,iv:oyV7fHKpEH8vbsAs3WYX8bGNOE4n3gyWKsh6e+1GZ9c=,tag:ppiYTz2o7pIfYt/SFXw0iQ==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:fQ4mY73JVXyfdKwCZQ==,iv:TsjZVjeyEy8YvjUrku0zwFQG6Wc7/swYIkyPVcObeQA=,tag:ewET3lmJ5W/P+Nxfrq4zWw==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:ywvPPYJHEHN4,iv:ITvMleFCHyCzRmu0a84eNagnm5OKZQuaBAS/xEVF0IU=,tag:IVR4BPMgq/gcX8CcHbeF/A==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:zuOymcHRsnjbG9cikK3Ah0USSdQ=,iv:ogJMT6+k+da2fVtcj4MdNpI/IbFoZS2uji8x2N7YSOs=,tag:nDKYrm9DtV27yeBibm9UBg==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:uxq860Q5qnUHJqrzpUhYHjnfm8I=,iv:ZXJx+g9dGbxC9bEesohzyEIRkygnG257SOgVuwEx/A4=,tag:5xb2QElIChUSOwgIICxbJQ==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:UTn4mKGRai7GX6Yxn/BlqOtNuG6FKk6UKKa+FjOAlLZVV+9idT+olw==,iv:aImnJ2H5Al5uEtibV1d2RA4E+fFR9P7ApdVdszTzgo0=,tag:PgVbqX3CmFkocMocrMzdIw==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:D+X6wuDq4JzWX8TLFv43nXCLe7nLg3IqVYZLpJ53YxsRx5koKw==,iv:WG7aCDD2v11bvbEQgzG+0A9GZnLT5Uzq5GJjr8p1BBc=,tag:+HyssYMq4HJPFpjF/MPiEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMnlPWTkvRU5EOVEzK0J3
            VmNvZmwxZ1RhbDgyQjFHbU40d0pOZ3QzeG5rClFaRkEyTlBpWi81MEJwTy91bUMr
            VE5YdWppMGdMcXRtS2FOY1VBeFRWM1EKLS0tIHZLMVpjbE5jRzhMZjJMakVOSEdD
            WmNDTXhPT3creG8xNTRncFdSZnJIMzAK5XpfHtGLAww1EJscshn/yTG9gf+4NXIH
            9Y3NALsFd8822lNJnQmZTUlHE1znE7CQLHkCrHs85nyfaCdOOBd7BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T05:42:33Z"
    mac: ENC[AES256_GCM,data:/mYsTLv2GenfyaWw1h+6i/Ns0d/rHigOR8OWKUJXh7cYqTGuEJq6l9starAc53mWEgf1vyUBkywnhgLMUJhVVdtE6wzqeO0C9Mv5zly8wBzHm65V+RxB7TseAmZjSAVclmpx8PUTij94HQKtpb8LWZc7Sa+JzkejMYp5YybCJ3M=,iv:eywLba0t/kCifjBhRSPiZ/TgqBuz2w0aBocILOFLwjg=,tag:DZa5XSZO6k2y2XasYKDlUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
