kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:2r1JAmYqLk9ZgC/UlDy1OWx03R20mRXTKWU85R7gH/1JCLAlOX6ruBZOpf/aFg76YMP+0lk=,iv:BvdudAEdxzB7GCipFnslnJn+Cy59CVOLi6QxJAwePyM=,tag:fqNWVJuQ0N2YQ+IqibFT0A==,type:str]
    github_user: ENC[AES256_GCM,data:FPblOSKmah78wQ0KmOQ=,iv:A6lVONfxn9Pocr8Qa4Dth8F6aYTsR6iDA8X0KAV2B70=,tag:8ttUbM1zHK8Mci8wXCv8kw==,type:str]
    github_api_token: ENC[AES256_GCM,data:rVVlMDuFhhJrdHf2ta5x7sm0OuiG7VYJ3BMo/8lTqstEdrqPfJXJrA==,iv:bRoNKHeaSXHEeq9wGDDdi+fkBql8UHWJOODq1cZtxRQ=,tag:QaMevWhSfJ3r+Rr81qtIzw==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:1BOKY68poHU=,iv:lXHU9Y7ijvW1QhDlvzSUl7TjHBLB7soEUbhPEr4m1sg=,tag:VzJRpRC25Mq+arty5i9dgg==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:yDyn3xDkBAFP5njKRbLsF9lx/MQEB+b0/M2HYYH7JdlMb28t,iv:ZrfShxFxuhXMiNlsE0e/enm3FmMTwBO6OgyyzsoLC3E=,tag:8btqnXZBCzUGEnz3J/Xxqw==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:61hBWFape3f//lQ=,iv:j7ulMM5KPDImq/ATkN1B5dmhre/zAzJNtznGsesCFGE=,tag:Tz/EtsgzucuNm2z8y+6JyQ==,type:str]
    prism_central_user: ENC[AES256_GCM,data:pWRWdLg=,iv:NABV3ezQGpX2MiGPa9E9+V3fd7QFn0ExduhJYgFQDJc=,tag:ZKpGyRUTu/BOYfvDXSnJ2w==,type:str]
    prism_central_password: ENC[AES256_GCM,data:roDIB+1vD1uDfbc=,iv:gc9EYg2kD0yp9QTG3v/g7WC2MuWSHjF4xU3g3Te91Hc=,tag:ixisgIIluKDqNw71kxxbjQ==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:9ZFgjjIrZBe2ddJqdhR6pOrrV2M=,iv:5bwopTlrE/1KjQN2N5sQuyrjWlZLkuuGKmdma+3lMOY=,tag:7p2wsHgNFY2CjeUY3/n2Qg==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:0g490Lx19Ra/KDg7mP4ZrEFSghW2aZdYD9hYHrAIxjfvEusaEJQ2Hg==,iv:zoxE0QTvuGpXeMcGljWwYz2twALeUBIPOE0BZIdxD/E=,tag:ToSnXNAULXC4PxjuSwjXtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTm5FNnU4bHdtOEZOK1pl
            V2NzM1hXcWpNSVk3T3BuSEwxN0MxMDBjbWg0ClVIQ3RGQ3dBZTlFN2tDWlI2cWg2
            d3l6Z2Z0dXF5SWMrMG45b1cyWmllNEUKLS0tIE1GSmtNVmN1V1IxekhRWldMUVRl
            Nm1lb2l1SWgrczhRRWNLY2RiTDZBd0UKA+SS5QpqR7VmpRds/RTEGf2hNoT0iYc/
            fvscCZjj4afTze8Rz/YUOke2j8IyiniX60SXtasgLpuAeYGlitrUDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T17:17:59Z"
    mac: ENC[AES256_GCM,data:jfXey+VAZ6tB51JEJsqkvfKy2/NtRUP4VSN5WBJh2jGj7VMWFTU3d/TCfpWxd7HWzYiFqwrgQf0hhM2pyQoZWZJ9jlb9h3gEkCiFJGzV/sB6P5vyhQCWku4CnzvGEi43vy2vp/L5SjxQEpKeKfxAtt8KFqvbd24/tiQIZoqzpaw=,iv:EW4/szFAbIoUQC40tzVbvdIc5UiVDIqqO6ArISfNTbM=,tag:A2KaXlfES7H2rA3CF89qJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
