kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:Od6P/3e+bzkFIJxKiwfvD4mgfhRG6lG+YQsFKXhk7tOCw79EVBSO+KlqXPTlWGVKxuSchZY=,iv:JH8W7gt3tBBk/exnK9GxT3ifuM4/sJewHHiWRj9m9oM=,tag:JPf8Os/JCpBoM3kjwICJFA==,type:str]
    github_user: ENC[AES256_GCM,data:j5NNyeMd4rvspaDzaGg=,iv:27IDutNmvXVlX0i+WgXiFa/SXJ+9s9P3CxYQ7bXrul0=,tag:2rxqRs5oxa75Qu6snvZPUQ==,type:str]
    github_api_token: ENC[AES256_GCM,data:EIzqE2GTIQ9PahlRlV60LUSKKUlKjhqMiETQaetjfGy7t7PWD038Vg==,iv:4O8KA9DLL1GWzQw9Q5BtAn4vbF0eiBp1XbeYKiyWG/U=,tag:oBI24Qcgnlx89WWdykITUQ==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:8hO0TD9R1gI=,iv:XHt+0oc4ES0KZCQpoCjKlfCXYZ2jZv8B+aqva2UToI8=,tag:TZQCkM5WuhAcU+RIT93UIw==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:QRc62IVYIpxFMNhvTKXwY/qKBbcz7m67kuLicnqRFOKS6Q0v,iv:ayQY7Tynr3LqEu9UfxJasxQLJmuxA3WnqvB2l0GjFJM=,tag:y5qIk8rnGmNQZWGewSIIpw==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:lHsUQ47sFJLV8u4=,iv:ZcdIQc910lbNuyJkq86jmk2MCBkRNEOUdVJzLWSVV+w=,tag:UTYrRRqJZn+ZIJN3NjqHUg==,type:str]
    prism_central_user: ENC[AES256_GCM,data:IpgZ9jM=,iv:2q22+97gF/xetAkZ1WgF+oUlzFxt5L/HVniRJfn8Ht0=,tag:C+vLT9DY8LpreCtk1cxIKA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:FuACmeejOMBDb5g=,iv:yVz+vvkO7uF13HkEivtwjppKIAG0dHGnHMw0HUuW0PQ=,tag:HX1hPwyPO09fKQzMoI1qQg==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:lDYosijoHDfax1Moo+6zjbiQ+y0=,iv:sMeOQeKwdWmgsBS8u3QakkyqEl0VqIPh+dcJGun3MBg=,tag:JCQUuvxJwETr+GWoEuaYSg==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:LNJXNXsaEmHTfyJqfVmkewlRMi8JuH7/7zDt0OBC/rEzXxgF4+mAxg==,iv:nOvGarCgsUlsm15wKdd88bo6BXcM/vXTKz7JRYlZFBA=,tag:SrhjP3ARTvoc26afHLrSbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYmwwVzlIRnFzYVJHRW9k
            bTZBSHJnUkdEZFRKcEFNUXRXUGVJVzVPdGg0CjdTdHIyVzdtcEd5TXRhOXh1c1U5
            VStRazJ0eTFGbnZGTDRrai9PZXlBamMKLS0tIHRGcXdzK1J3Y3BzaUI3VThFMlBS
            em5pdU14N205bUlGOWtuUXNJR3h3dlEKyq9RoweTXV7KYzqCGCNqVgsFQzK3HECT
            g273xc7q2aCkIB149TwxLcZNgaBghlcW0kw1owSiMNYkZdcXsm4O5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T17:16:10Z"
    mac: ENC[AES256_GCM,data:JpmQPnp1HvZQDg30qlIu48T6Y7SJ29AW2WhoA24khKkBnsedohLt60RsYJwWnKgaQyHkR9Xoq/3DQq8lzvi62+uLtDNVKjbKs7lUtYO1Gcbku9QgK6ALhRjtknDRywoobImFZzMhZPZCzTy0nsSivEStKJESN+CGsCRBsVOWa8M=,iv:fPtND/cMVZZ/wejM8sGoir2od6S4RsLKtGoAgqylfKM=,tag:exbEIfbBB7Xwvx8WwzgMIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
