apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 4h
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=kyverno}
  chart:
    spec:
      chart: kyverno
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: ${kyverno_version}
  interval: 1h
  values: {}
