## variables to pass into module

variable "github_org" {
  description = "Name of the Github repository where the flux bootstrap will happen"
  default = "jesse-gonzalez"
  type = string 
}

variable "github_repository" {
  description = "Name of the Github repository where the flux bootstrap will happen"
  default = "gitops-nai-llm"
  type = string 
}

variable "github_branch" {
  description = "Name of the Github Branch that flux will be pulling configs from"
  default = "main"
  type = string 
}

variable "github_app_id" {
  description = "Github Application ID to be used for Repo Integration"
  default = "813903"
  type = string
}

variable "github_app_installation_id" {
  description = "Github Application Installation ID to be used for Repo Integration"
  default = "46842190"
  type = string
}

variable "overwrite_files_on_create" {
  description = "Will force over-write any files generated by tofu"
  default = true
  type = bool
}

## variables to specific to cluster instance
variable "cluster_name" {
  description = "Name of Kubernetes Cluster"
  default = "kind-llm-management"
  type = string
}

variable "environment_type" {
  description = "Environment Type"
  default = "non-prod"
  type = string
}

variable "profile_name" {
  description = "Profile name to use from flux bootstrap repository"
  default = "llm-management"
  type = string
}

