apiVersion: v1
kind: Namespace
metadata:
  name: jupyterhub
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  interval: 4h
  url: https://hub.jupyter.org/helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=jupyterhub}
  chart:
    spec:
      chart: jupyterhub
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
      version: ${jupyterhub_version}
  interval: 15s
  timeout: 30m
  install:
    remediation:
      retries: 30
    createNamespace: false
    replace: true
  upgrade:
    remediation:
      retries: 30
    preserveValues: false
  values:
    singleuser:
      defaultUrl: "/lab"
      storage:
        capacity: 100Gi
      extraTolerations: [{"key": "dedicated", "operator": "Equal", "value": "gpu", "effect": "NoSchedule"}]
      extraEnv:
        JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
      profileList:
      - display_name: "Minimal environment"
        description: "To avoid too much bells and whistles: Python."
        default: true
      - display_name: "GPU Server"
        description: "Spawns a notebook server with access to a GPU"
        kubespawner_override:
          extra_resource_limits:
            nvidia.com/gpu: "1"
      networkPolicy:
        egressAllowRules:
          cloudMetadataServer: true
          privateIPs: true
      cloudMetadata:
        blockWithIptables: false
    hub:
      config:
        Authenticator:
          admin_users:
          - admin
        DummyAuthenticator:
          password: ${jupyterhub_default_pass}
        JupyterHub:
          authenticator_class: dummy
    proxy:
      service:
        type: ClusterIP
  valuesFrom:
  - kind: ConfigMap
    name: cluster-configs
    valuesKey: jupyterhub_overrides
    optional: true

