apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  knative.dev/crd-install: "true"

resources:
#- istio-crds.yaml
#- istio.yaml
- https://github.com/knative/net-istio/releases/download/knative-v1.10.0/istio.yaml
