apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative-istio
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager-resource-configs
  - name: kube-vip-resource-configs
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./platform/knative-istio/_crds
  prune: true
  wait: true
  timeout: 15m
  postBuild:
    substitute:
      namespace_name: istio-system
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative-istio-operators
  namespace: flux-system
spec:
  dependsOn:
  - name: knative-istio
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./platform/knative-istio/_operators
  prune: true
  wait: true
  timeout: 15m
  postBuild:
    substitute:
      namespace_name: istio-system
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative-istio-resource-configs
  namespace: flux-system
spec:
  dependsOn:
  - name: knative-istio-operators
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./platform/knative-istio/_resource-configs
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: istio-system
    substituteFrom:
    - kind: ConfigMap
      name: cluster-configs
      optional: false
    - kind: Secret
      name: cluster-secrets
      optional: false

