apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- ../../_base/kube-vip-repo.yaml
- ../../_base/cert-manager-repo.yaml
## custom ingress nginx deploy for kind clusters
- ingress-nginx-kind-deploy.yaml
- knative-istio-repo.yaml
- knative-serving-repo.yaml
- knative-eventing-repo.yaml
- kserve-repo.yaml

patches:
- path: kserve-addons.yaml
