apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-demo
  namespace: flux-system
spec:
  values:
    components:
      frontendProxy:
        ingress:
          enabled: true
            annotations:
              cert-manager.io/cluster-issuer: ${cert_manager_issuer_name}
          ingressClassName: nginx
          hosts:
            - host: otel-demo.${wildcard_ingress_subdomain}
              paths:
                - path: /
                  pathType: Prefix
                  port: 8080
          tls:
          - hosts:
            - otel-demo.${wildcard_ingress_subdomain}
            secretName: otel-demo-tld-secret
