kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "nai-llm-gitops-prod"
  environment: "prod"
  cluster_profile: "llm-workloads"
  gpu_cuda_toolkit_version: "v1.14.3-centos7"  
  kube_vip_ipam_range: "10.38.110.22-10.38.110.23"
  kube_vip_nginx_ingress_ipam: "10.38.110.20/32"
  wildcard_ingress_subdomain: "nai-llm-gitops-prod.ncnlabs.ninja"
  management_cluster_ingress_subdomain: "nai-llm-gitops-mgmt.ncnlabs.ninja"
  kube_vip_istio_system_ipam: "10.38.110.21/32"
  aws_route53_dns_zone: "ncnlabs.ninja"
  aws_route53_region: "us-east-2"
  objects_host: "10.38.110.18"
  objects_port: "80"
  objects_region: "us-east-1"
  objects_use_ssl: "false"
  milvus_objects_bucket_name: "nai-llm-gitops-mgmt-milvus"
  documents_objects_bucket_name: "documents01"
  model: "llama2_7b_chat"
  revision: "94b07a6e30c3292b8265ed32ffdeccfdadf434a8"
  maxTokens: "4000"
  repPenalty: "1.2"
  temperature: "0.2"
  topP: "0.9"
  useExistingNFS: "true"
  nfs_export: "/llm-model-store"
  nfs_server: "10.38.110.47"