kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:+z87SAnI64be1Lq75kxnaUAJhlru0kiJ247FMKuNvL5XX+LszBOVXejyPTRW9V8TiziNklg=,iv:GrSYJDNFyYXjns+RW3OBjO7BjMKjopZ01HOMjdHhYzw=,tag:Crj5Zx8FLhUwri43bUKjSA==,type:str]
    github_user: ENC[AES256_GCM,data:QB/Xn+S0ej7X68jp2xs=,iv:VPGW58xwx/TvpBmDnceYq190N3hO6AxkJx4V1csZ2ak=,tag:BRsBmxc/bcYp0ARkQDymSg==,type:str]
    github_api_token: ENC[AES256_GCM,data:QivdznM0oE2z2D04AhVKkq+uW1N5KQebsohsLTwFWJ476EHb+L76HQ==,iv:zOTzvUxLtXcWGDIa8V+0wmOGZJS6c2y3Ajicf5yX8BQ=,tag:VHtkKA5CJ4Aoacfy4qlH1g==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:nQUfCTwTTco=,iv:WFU0F74Dw0pJVsUW4oMsGxxEqheHTR8KFXEY0XNa26M=,tag:ACStTloW/r5eTB05kf9Dug==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:J+cWXDcEzdSSGmnyIoBnEM6bfHQi1R/xk2KHgD80Qz6C0Kv0,iv:CxS9giXLmbSL8S4WViA0b3kqid1OjIykITMj+ciEpEE=,tag:W6W+hU6+rR85oas/jAkwUQ==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:7uGXS2dTGAB2WrFJ,iv:ZWndyr7n9e0leB7bbbS35Zryw6h3X+oIKBc4ylLwhZE=,tag:wDOqVc9F+EjNbvIFMo/Pjw==,type:str]
    prism_central_user: ENC[AES256_GCM,data:ZRGjeH0=,iv:lWvv0HlqBZx091DaLdhc+sJJUgB3yYQDNy3vkImDk40=,tag:Pox7hn1BhOPirW6ic9fo5A==,type:str]
    prism_central_password: ENC[AES256_GCM,data:OKKr8RNcM6laMcM=,iv:2BAeDsAi4DB5pUA11pihbt6X7sgyWkzldj2pyg4oJCk=,tag:harfrGpc+8Jnn2SxPvVlIA==,type:str]
    objects_host: ENC[AES256_GCM,data:DMBKcLRxTbSo7XAf,iv:VQkCu1eGZowm6PertN8osxqUU7XXGJBL8nlAu6VWD0E=,tag:PCCCvIZBvVwY/b4mOtTbaQ==,type:str]
    objects_port: ENC[AES256_GCM,data:gOM=,iv:2QEe2bGIiIfD4YPrE1ckvZnaYD+XObcrM2AwMjANrkI=,tag:NwiUAz5C1w6ZojOZnc8z+Q==,type:str]
    objects_region: ENC[AES256_GCM,data:ctZ8PrKF3MnW,iv:O4c9u5BHF47pxUuCzKu4nrEL/HSA9Q+0ceCzEKKpTzc=,tag:hkZOmNQ3D8Y1Rk4o3b5NBA==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:F4r/f5Y=,iv:eeCgGlYFesZAqCbIG7qH0oPt9jvy3eG3dm9AZc2dxX0=,tag:TO1TjcEhtwiZaU0amhJMAg==,type:str]
    objects_access_key: ENC[AES256_GCM,data:7vyudgczyjOjqakybfH+x6hTCQHe19qC6UWU6yRIyjs=,iv:MRlfbrGTUDxI6gf7QpbeANnvDdo2iSPRdmlxAyJofOk=,tag:4s99UpNWXAXKVDs/TFK0Kg==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:VsmWeJSFJ8dmrmqbY94hampEVBjsxiOQEohHVAo+jQs=,iv:/hsQ+SIZoUSV+MM3CROfXrxhY57LH5c668rFDwoOhow=,tag:ET/mxAYgQJxbEY/KTChVDQ==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:C01AUzKIpzaBo6/dd2IyLgax9ZazhMIwZA==,iv:/dDVKKXPsB7YimdaT9uSn2YhHKKNZNdsr25pL+UqFqg=,tag:ec1qJksKyB+Qmy//5i85iA==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:91jM85AXIsN7CeMPRRmZ,iv:OXF6HM0n5P3N3f/18ek3cEgyLid7KJ4AE2SInYqnbDY=,tag:vv+ZmZA1VP6DUG9jQLi6nA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:NybatCGvcVZK0Yh3IsoO509u3OBYw4z0W9wdNAO0oNMw,iv:48l4fp8j8INg0T5WqQc+RuoDQNHwur04BNvmdohTIrc=,tag:sODs3l+IdoaZqCH0hJK16g==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:KP6YEMFE3gq9CTk7OPSNDGIRpe58Ng7OXHkufzQP9+cc,iv:TV87N/MgshgT6R+0IH0MLc0NQI951RgNRZy1hX508TA=,tag:e8J9mtMPLgfhbwIfo1M6hg==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:fDnxCE91mSMfjmYPlRSG,iv:1OBK6x+pAja8QlV73ekCtRugdyGk6xG+IJ8LI+olBbI=,tag:EEW9pwXFGlLV659vJkXGJg==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:DHxhEoCfhw1Fsx9GpAjnrUThrkMP8EmLUYa+pK7Fufq3uIi5bw==,iv:hkc22TYsg1UDXTu3qfNxtZsg13aSLQX2HdwDvLpeQo0=,tag:fA1EzcabOhXT+tEPAv/AKw==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:up5f7V6OZmG2smFIyqdycG9I,iv:eSlZvKGev4iEuNueWwonKD7GEKfcVsEg8cizLcXRUtI=,tag:O4br7ry/T4nSOAyn0o6TBA==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:P5S6OsPt1INdHSRgTg==,iv:X6whA52GsmDg/mKNM+kjDYxeYYKxAhHk/RW1XJiZuYk=,tag:8HgNNwOVU+yHK5+eQefwlw==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:SW2NY6iQTBts,iv:iW3yf2baZAofhGYK1XvCf45WJFbukLXHqbRF1aMChrY=,tag:avbuZkfz66sjuwDFTb9e0A==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:yxIzdMV6vRkcpahxFHRae66rX9U=,iv:ELsolcUcPpB4GdY9X3xdw73OL68Vbh1JQPY9CEz5xWE=,tag:Ux+1ute0ZMoi4egTZ79Img==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:PzH0NZXbso5X7ExYwS+/0iwZNb0=,iv:3itvr1U3JlLs+jrHpHR1AZzotMKeYaTzWVl20BWdxvM=,tag:iqUgl19/TgHq5W+sQx4fMg==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:9xzzy/htXxfZENb/VIIG9ztAeP6uPvw7HmpSYsVqWYOXuQQ551SMFw==,iv:4zM1Yd9bXmtLH/5eJr6sM8okx0VLTy29cPcvMGqE2xU=,tag:vQLrPkjvFZFPuA0M0q1eVA==,type:str]
    nfs_export: ENC[AES256_GCM,data:GjVOqVOdkXxfXWtluTld9w==,iv:ytd/ClTlgmuH+2dgd1nfZKkPV+gheg48kERoCC5reSU=,tag:8SHbSZwI/Gt2xtAtc9Nkbg==,type:str]
    nfs_server: ENC[AES256_GCM,data:hgjdvifBZRGozdVC,iv:R8G1RWBtatkm7uoSYral5WffAOO1UuKIcyOYdzSNhSo=,tag:iQRCDypbTika+9yecqaWZQ==,type:str]
    huggingFaceToken: ENC[AES256_GCM,data:JHYHvCZPZWgTArL0CYNP+WxUz2bh2a7a9M+a6XWf2qlDuKao9Q==,iv:KectDY3Bn/sq1lzRk6Xdd5oRFM+d1XMdlAsVSGjz2Zs=,tag:ExlKVeYcrbqktj9PwBHFlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOTB3REx0VG5kdU40cnlj
            c1ZDOUtSelNCWk00c1hsN1pIL1V5Y1ExRHpNCmVJbHdWNmpXOHJMZTg1L0VlWklk
            NmI4cWVOR3VSbndFb085clM4NkExOXMKLS0tIDJmU2Q3Wm5RZ1ZPTDJIMUxLNWRX
            K3hidVdpTk9jdTlFSGJOTlRKeEhGL2sKWXKJ6ZkAotkiQYN4WpM2Rxg0gfe5fzDF
            Iok+o9AiJnsnaXVsBjzr/q0hARD39kMZQ0y//NA3UFseZSLxhPlw0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T21:39:10Z"
    mac: ENC[AES256_GCM,data:1bWwkxtDqLoSo16u1cQevkSwvoKLGjo0mTFUeQYu0wOjRIV1VR/A+yHJyGoGwCRHKhVjR2B2/lf54/Q9xq7yzjY3O0dOClmrrAnpoDlj2R8F9uFLaW03G+0gJGB6oIlQhRrOX4CYUUM/aGaQDU163VHdX4Hc3ESMGRljOGnepeY=,iv:9UiXNDunonI35DQDleSUqSgNRfRa0WsLVggNyBX5RN8=,tag:MSM7ZlTklabb6hmFUklchw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
