apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: docker-hub-regcred }]
  target:
    kind: Deployment
    name: kserve-controller-manager
    namespace: kserve
