kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-configs
data:
  cluster_name: "dragon-dev01-w01"
  environment: "non-prod"
  cluster_profile: "llm-workloads"
  gpu_cuda_toolkit_version: "v1.14.3-centos7"
  gpu_operator_version: "v23.9.0"
  gpu_time_slicing_replica_count: "2"
  nginx_ingress_version: "4.8.3"
  istio_version: "10.122.7.66"
  cert_manager_version: "v1.13.5"
  cert_manager_issuer_name: "letsencrypt-issuer"
  documents_objects_bucket_name: "documents01"
  milvus_version: "4.1.13"
  milvus_objects_bucket_name: "dragon-dev01-mgmt-milvus"
  kafka_version: "26.8.5"
  model: "llama-2-13b-chat"
  revision: "c2f3ec81aac798ae26dcc57799a994dfbf521496"
  maxTokens: "4000"
  repPenalty: "1.2"
  temperature: "0.2"
  topP: "0.9"
  useExistingNFS: "true"
  kserve_version: "v0.11.1"
  knative_serving_version: "knative-v1.10.1"
  knative_istio_version: "knative-v1.10.0"
  kyverno_version: "3.1.4"
  opentelemetry_collector_version: "0.80.1"
  opentelemetry_operator_version: "0.47.0"
  uptrace_version: "1.5.7"
  weave_gitops_version: "4.0.36"
  jupyterhub_version: "3.1.0"
  jupyterhub_overrides: |-
    hub:
      config:
        Authenticator:
          allowed_users:
          - wolfgang
          - jesse
