apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: milvus
  namespace: flux-system
spec:
  components:
  #- ../enable-loadbalancing
  - ../enable-monitoring
  #- ../enable-attu-frontend
  #- ../enable-nutanix-objects
