apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: flux-system
spec:
  interval: 4h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector-daemon
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=opentelemetry}
  chart:
    spec:
      chart: opentelemetry-collector
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      version: ${opentelemetry_collector_version}
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
  values:
    imagePullSecrets:
    - name: docker-hub-regcred
    mode: daemonset
    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: true
      kubernetesAttributes:
        enabled: true
        # You can also configure the preset to add all of the associated pod's labels and annotations to you telemetry.
        # The label/annotation name will become the resource attribute's key.
        extractAllPodLabels: true
        extractAllPodAnnotations: true
      kubeletMetrics:
        enabled: true
      hostMetrics:
        enabled: true

    extraEnvs:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: "status.hostIP"

    config:
      receivers:
        kubeletstats:
          endpoint: '$${env:NODE_IP}:10250'
          insecure_skip_verify: true
      processors:
        batch:
          send_batch_size: 10000
          timeout: 10s
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
      exporters:
        otlp/central:
          endpoint: opentelemetry-opentelemetry-collector-deployment.opentelemetry:4317
          tls:
            insecure: true
      service:
        pipelines:
          logs:
            exporters:
            - otlp/central
          metrics:
            exporters:
            - otlp/central
          traces:
            exporters:
            - otlp/central
