apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gpu-operator
  namespace: flux-system
spec:
  interval: 4h
  url: https://nvidia.github.io/gpu-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=gpu-operator}
  chart:
    spec:
      chart: gpu-operator
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: gpu-operator
      version: ${gpu_operator_version}
  interval: 30m
  timeout: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    preserveValues: true
  values:
    toolkit:
      version: ${gpu_cuda_toolkit_version:=v1.14.3-centos7}

