apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 4h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=kafka}
  chart:
    spec:
      chart: kafka
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "26.8.x"
  interval: 1h

