apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  components:
  - ../enable-prometheus
  - ../enable-letsencrypt-aws-issuer
