kind: Secret
apiVersion: v1
metadata:
    name: cluster-secrets
stringData:
    github_repo_url: ENC[AES256_GCM,data:edEA6R4TwSD+AMiKVGFY8HkHjgZ1W44Pamt6MVuDhncPdfrX3GPboUozxnKw6BWXGHpt8oQ=,iv:8TKzshOBLvvv/vwwl2RUZYXgz+RyMm1a89b8uPCXCvU=,tag:G1ZLFjeUpjU6tADkWJ6jlw==,type:str]
    github_user: ENC[AES256_GCM,data:l8bVkjvhf2kJUDYXOp0=,iv:hMVhDOQnASDzuyOTArvwR+NqXGOYHPqwJKVXGBPsUus=,tag:1sTjSrpVXMEzEe0//W2BFg==,type:str]
    github_api_token: ENC[AES256_GCM,data:nnl/DHowTVzptnSBgGyB+Mx7JricnB2fPDOuDcujvfWYd+Q0SjdnfQ==,iv:+RYP+RFsewqR8/dYdJT9ZeP0Im4H73OmfvJFT9UxGUU=,tag:zERYAPiqvarAuh9Z9o8dfg==,type:str]
    docker_hub_user: ENC[AES256_GCM,data:FRK4386iq74=,iv:O8irPxqWu+1g4G8JUayNHiFdsfKlUzfWa4/oJGOh78o=,tag:Uq6l8IUzjtxqF5LcR1Oe4w==,type:str]
    docker_hub_password: ENC[AES256_GCM,data:jb0gqWugDy5agu2EwHE/x7qhu5XwSoARHMerqNx+Dpf2vfTl,iv:Io98B7TVI4HSgaN8RtlRLAJftYfuc55jqk76B2vcX1M=,tag:iM4kCVhAPfXWKu4GR4bIBA==,type:str]
    prism_central_endpoint: ENC[AES256_GCM,data:R3oZXaN03hewZzqanvldPuFkHdfgAEYsbk+tcwyJkgg=,iv:Ig33h+Muz5wKNltPVNvP/wKBpGaRYS6FSPIlaYTHNR4=,tag:0YsLIFm7aXw5WIXI6ENTgA==,type:str]
    prism_central_user: ENC[AES256_GCM,data:5KuSzn4=,iv:Uv00RrYX/N5PbOUyRqGrmuDFdi6vubr+lAcYPpj4xmY=,tag:XFoBWBYSYSiYzt2+xhLbOA==,type:str]
    prism_central_password: ENC[AES256_GCM,data:L9UgU6PbaMcsRXw=,iv:UyRb+Ad6M/TjzHuULqcJXeaf7Vl3j8l3LVRlVYyZnKo=,tag:9ULKtybZX80sEJeceM5uYw==,type:str]
    objects_host: ENC[AES256_GCM,data:K1/OhbaiVNByofrYdpEbmEtdCo6mRvrdKs1cD5IHO48olJxFMg==,iv:zToDaRc/qGGkwowm6BMoDop3sOkcpx6p87jIhK4ALrY=,tag:YBrMJ4qiQKCYqX1bME/Ohw==,type:str]
    objects_port: ENC[AES256_GCM,data:fBs=,iv:vjfQ7vMaicAWLjxuzgjT+sStqyov/5Tc1FPmSW0py8U=,tag:J5OJ4d6hLeAal2bg/hkE/w==,type:str]
    objects_region: ENC[AES256_GCM,data:M8e76CyGEKmY,iv:uthijrLZ5LrJlRrEr3nn/ezxgxLFjk449hGG/YwW4Eo=,tag:TYiovCaM+AxxyLc65nsfVg==,type:str]
    objects_use_ssl: ENC[AES256_GCM,data:WS5QMw==,iv:oSpQm55IeaFDTIECk06IgkOOTe3MlOJuBisD7dfSdfU=,tag:4wa2g79XMIHruq5s+Fns2A==,type:str]
    objects_access_key: ENC[AES256_GCM,data:JdIoJFfF3vD1g7sdISnjzXZiWaHmxZpGQBYvaFPsVj8=,iv:wyMkJcUnng+As7+xmm4pznC89NKHGhKV1mV+HHvflYo=,tag:IXDk4rvIn89u2TqLUHsTyw==,type:str]
    objects_secret_key: ENC[AES256_GCM,data:Zvxd3NInwlW+f51725ICmwmxfFF+Gb8RJlI9ipG29+I=,iv:dqwjVNxlMT27iBiQogKWoKx7BVGwuyDltV7Wx8lXz8o=,tag:G4PwW5lrWeDcfxWAFIbCVA==,type:str]
    kube_vip_ipam_range: ENC[AES256_GCM,data:rkisPrvPq88gjUU7iHFoP/319CaTti3vLg==,iv:745FEo+jZVl5z+Koifv6JQYYV8HB/yYfW2Wd0CmqcNw=,tag:DnnMBqe15QRTWA6Dp/W7Cw==,type:str]
    kube_vip_nginx_ingress_ipam: ENC[AES256_GCM,data:66zl7rjZlaeieFg392b6,iv:iLNiPH3cEpf4b+t5GcKzHwza1V57tf0w97Qh+bMmvzw=,tag:KnJBg58II1i7C2gKhZo1zA==,type:str]
    wildcard_ingress_subdomain: ENC[AES256_GCM,data:cMSbggSyT4fvlr3hC1YXT6rr2byX8dzbeXRwrlRxBmFAD9MlRrt7hI4=,iv:XjUGmkvNrcGwWknMZlM1rm/6YD4QdmO7IScb8Ke+0UQ=,tag:4D5mf5xvOt4vYuJCZhvOdA==,type:str]
    management_cluster_ingress_subdomain: ENC[AES256_GCM,data:pYGls96aQJdmsTpS+7Ts/mqtW+TDgixvSrpaxuOOet5TrcYi9/ITCrQR,iv:F9N/92Hp24mneOSz486vcgl6ox8peT/wZY0GDBCpB4g=,tag:Ugq6fOPqh3pLwI5j2aDMDA==,type:str]
    kube_vip_istio_system_ipam: ENC[AES256_GCM,data:dZ24uAReY7P+NwgIhtvF,iv:fNP6EnFL7AGB2nAH1kuZOBDCZHIBUGAyINrNlKf7gv8=,tag:JMvx/AJyRfOzt44zDMdhbQ==,type:str]
    istio_wildcard_ingress_subdomain: ENC[AES256_GCM,data:aB9IuwMghixvUsffVeQmp9C9Vev2ezXj73JMR5GISTfYKIJtzyXWzxuzs+T7,iv:JVmp9ELSaooVuVOTQfskr3cyUzdW+NXrmS+EwTTzXCo=,tag:axPfpQIXUgWx3bKFQ/G1Kw==,type:str]
    aws_route53_email: ENC[AES256_GCM,data:dfIIZEmFRov6b0XdnYo2c8IqlIqmM5TEiQ==,iv:5wjsmmlfRezG7h3ussPjzAtWVngfVic5IKqBM2gilj8=,tag:GXu7TqItWz/7p3hxnIeSNQ==,type:str]
    aws_route53_dns_zone: ENC[AES256_GCM,data:SvdMY+LJxdddCapspXJS4gvW3th3Mg==,iv:L7YEq5c/NPKq5YTKctjuqiPDAlg5qqPwbl8AdZ0wr8U=,tag:+8/E5b4Ykr0Fr1IpbJtYkg==,type:str]
    aws_route53_region: ENC[AES256_GCM,data:KdAjwLn14L+o,iv:W7FFR3tkuYiawN+ZXWvd0c/Z0IHbeT4MXfuiUR/YVAI=,tag:zfZtdrb16DGYO5zOA9bKSw==,type:str]
    aws_route53_hosted_zone_id: ENC[AES256_GCM,data:meOozG3fsj6UJggLYfaYUE4lvpKz,iv:L1nmfnn8V+8mP8aMmkmCQX0yZZbBvXI3e9BnVseei7M=,tag:XKghWlu/FRyNSFZA2bUHVA==,type:str]
    aws_route53_key_id: ENC[AES256_GCM,data:PuZT6DGUX8eGMH/n2ZUpv3aLcu8=,iv:Kxy/2wi/b45G+FnLKjVraBfTq0qpL1ZVJBRGyfk7csU=,tag:4J8sUcfEs3toJYoV2n4mbg==,type:str]
    aws_route53_key_secret: ENC[AES256_GCM,data:ljcOGyFC8Q6a+w1GrGfn5RBnf5jAatp+K24glkOOZ1mQ2t7IfE+6xQ==,iv:NX/rtUrpRBynHFBEVaqHg+/dPpvj3SDIGeLsf8lzOTU=,tag:YYQS6veumLbo/8J/cU/hFQ==,type:str]
    nfs_export: ENC[AES256_GCM,data:5W7bz6dTr0ptnIGqQg==,iv:jPlbq8qSQI67SRTOPOI/rern6/VaDq1WB6QcmRY81w0=,tag:mDvYtmMUUKfFpSo8O6Ux9A==,type:str]
    nfs_server: ENC[AES256_GCM,data:/3TJaAoHHF8kaaykL2n46Gxr5Cr1baCqJ4jnTf+HKdVQjNs=,iv:LkWvzaQeMs3MN5QGJ+b8EXJmFPn4z2RljrLEJVlKxZs=,tag:5tpgrs9mQp3uVfp6VkzECg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1apnz8w62yg00n3lux9ys8w59e5pxqqrg28dgzy6ajkr82aeq09gslhhm3n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdE5QajFSczlINHZhQ0xP
            VWVqSHRacVVBWlJoL0lzc21vOWJCeTZXWDJ3CjFzaXYzdktHS2xoUjhGN3o2N3Fp
            WnYwcUFxNHpPNjVqYTVIVnc4WWdYVFUKLS0tIFExVmw4Z3grZlM3L2lMWGIvVkIz
            QWRWT1Y1RnN4NUtCNEE3czVtUENuMjQKTcirXaJHWjEw7RiHLVhz6YkmMgP1+Ahx
            my1LO8eUOeH93gsohUE1KO8vmlCWeWZMyN4VJuFGxYiRxwo38iDGAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T19:29:44Z"
    mac: ENC[AES256_GCM,data:mItOhvmjHP5mDstzLTQ1oCUwkLhn63jpKZKl33um/Bjmfe6F3jJXSIPfh1ozURdcd0IdL3wkKn0tWMsB5mDb85hDTA4HZ5dBNlzROj3tw+r/kwohWSlSmfxTfF5BgJhLyeajlXnxKrnwBnxYxXOo3DEjxX5GAA5t0YAH1avwm90=,iv:IAExalQ76sYs0Gr8SnssFdXBv6T4fAEI+yIlvpSj/WY=,tag:+a2MCVXb1dQQXw62r3pbcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|auths)$
    version: 3.8.1
