apiVersion: v1
kind: Namespace
metadata:
  name: uptrace
  labels:
    toolkit.fluxcd.io/tenant: platform-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: uptrace
  namespace: flux-system
spec:
  interval: 4h
  url: https://charts.uptrace.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptrace
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name:=uptrace}
  chart:
    spec:
      chart: uptrace
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: uptrace
      version: ${uptrace_version}
  interval: 1h
