apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
      - jupyter.${wildcard_ingress_subdomain}
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 900m
        cert-manager.io/cluster-issuer: ${cert_manager_issuer_name}
      tls:
      - hosts:
        - jupyter.${wildcard_ingress_subdomain}
        secretName: jupyter-tld-secret
