name: e2e

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
    - '.github/workflows/e2e.yml'
    - 'clusters/_profiles/kind-stacks/**/*'
    tags:
      - v*
  pull_request:
    branches:
    - main
    - feat**
    - bug**
    - task**
    paths:
    - '.github/workflows/e2e.yml'
    - 'clusters/_profiles/kind-stacks/**/*'
    - 'plaforms/**/*'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
env:
  K8S_CLUSTER_NAME: 'flux-kind-cicd'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flux
        uses: fluxcd/flux2/action@main

      - name: Setup Kubernetes
        uses: helm/kind-action@v1.7.0
        with:
          cluster_name: $K8S_CLUSTER_NAME

      - name: Install Flux in Kubernetes Kind
        run: flux install

      - name: Create Flux Source GitRepository
        run: |
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=${GITHUB_REF#refs/heads/} \
          --username=${{ github.actor }} \
          --password=${{ github.token }} \
          --ignore-paths="clusters/**/flux-system/"

      - name: Create Flux Source GitRepository
        run: |
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./clusters/$K8S_CLUSTER_NAME 

      - name: Verify cluster reconciliation
        run: |
          kubectl -n flux-system wait kustomization/weave-gitops --for=condition=ready --timeout=5m

      - name: Verify helm reconciliation
        run: |
          kubectl -n flux-system wait helmrelease/weave-gitops --for=condition=ready --timeout=5m

      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces
